import { Router } from "express";
import blogsRouter from "./blogs.route";
import choicesRouter from "./choices.route";
import exercisesRouter from "./exercises.route";
import followersRouter from "./followers.route";
import forumCommentsRouter from "./forum_comments.route";
import forumLikesRouter from "./forum_likes.route";
import forumMediasRouter from "./forum_medias.route";
import forumRepliesRouter from "./forum_replies.route";
import forumsRouter from "./forums.route";
import mediaTypeRouter from "./media_type.route";
import questionsRouter from "./questions.route";
import userExerciseHistoryRouter from "./user_exercise_history.route";
import userSavedBlogsRouter from "./user_saved_blogs.route";
import userSavedVideosRouter from "./user_saved_videos.route";
import userVideoHistoryRouter from "./user_video_history.route";
import usersRouter from "./users.route";
import videoCommentsRouter from "./video_comments.route";
import videoLikesRouter from "./video_likes.route";
import videoRepliesRouter from "./video_replies.route";
import videosRouter from "./videos.route";
import gradesRouter from "./grades.route";
import subjectsRouter from "./subjects.route";

const adminRoutes = Router();

adminRoutes.use("/blogs", blogsRouter);
adminRoutes.use("/choices", choicesRouter);
adminRoutes.use("/exercises", exercisesRouter);
adminRoutes.use("/grades", gradesRouter);
adminRoutes.use("/subjects", subjectsRouter);
adminRoutes.use("/followers", followersRouter);
adminRoutes.use("/forum_comments", forumCommentsRouter);
adminRoutes.use("/forum_likes", forumLikesRouter);
adminRoutes.use("/forum_medias", forumMediasRouter);
adminRoutes.use("/forum_replies", forumRepliesRouter);
adminRoutes.use("/forums", forumsRouter);
adminRoutes.use("/media_type", mediaTypeRouter);
adminRoutes.use("/questions", questionsRouter);
adminRoutes.use("/user_exercise_history", userExerciseHistoryRouter);
adminRoutes.use("/user_saved_blogs", userSavedBlogsRouter);
adminRoutes.use("/user_saved_videos", userSavedVideosRouter);
adminRoutes.use("/user_video_history", userVideoHistoryRouter);
adminRoutes.use("/users", usersRouter);
adminRoutes.use("/video_comments", videoCommentsRouter);
adminRoutes.use("/video_likes", videoLikesRouter);
adminRoutes.use("/video_replies", videoRepliesRouter);
adminRoutes.use("/videos", videosRouter);

export default adminRoutes;
