import { Router } from "express";
import blogsRouter from "./blogs.route";
import choicesRouter from "./choices.route";
import exercisesRouter from "./exercises.route";
import followersRouter from "./followers.route";
import forumCommentsRouter from "./forum_comments.route";
import forumLikesRouter from "./forum_likes.route";
import forumMediasRouter from "./forum_medias.route";
import forumRepliesRouter from "./forum_replies.route";
import forumsRouter from "./forums.route";
import mediaTypeRouter from "./media_type.route";
import questionsRouter from "./questions.route";
import userExerciseHistoryRouter from "./user_exercise_history.route";
import userSavedBlogsRouter from "./user_saved_blogs.route";
import userSavedVideosRouter from "./user_saved_videos.route";
import userVideoHistoryRouter from "./user_video_history.route";
import usersRouter from "./users.route";
import videoCommentsRouter from "./video_comments.route";
import videoLikesRouter from "./video_likes.route";
import videoRepliesRouter from "./video_replies.route";
import videosRouter from "./videos.route";
import userContentRouter from "./user-content.route";

const router = Router();

router.use("/blogs", blogsRouter);
router.use("/choices", choicesRouter);
router.use("/exercises", exercisesRouter);
router.use("/followers", followersRouter);
router.use("/forum_comments", forumCommentsRouter);
router.use("/forum_likes", forumLikesRouter);
router.use("/forum_medias", forumMediasRouter);
router.use("/forum_replies", forumRepliesRouter);
router.use("/forums", forumsRouter);
router.use("/media_type", mediaTypeRouter);
router.use("/questions", questionsRouter);
router.use("/user_exercise_history", userExerciseHistoryRouter);
router.use("/user_saved_blogs", userSavedBlogsRouter);
router.use("/user_saved_videos", userSavedVideosRouter);
router.use("/user_video_history", userVideoHistoryRouter);
router.use("/users", usersRouter);
router.use("/video_comments", videoCommentsRouter);
router.use("/video_likes", videoLikesRouter);
router.use("/video_replies", videoRepliesRouter);
router.use("/videos", videosRouter);
router.use("/user-content", userContentRouter);

export default router;
