export const mockTitleDescriptionTopicAndType = [
    {
        title: "Challenges of Learning Math in Cambodian High Schools",
        description: "Many students find math difficult due to large class sizes and limited resources.",
        type: "article",
        topic: "Math",
    },
    {
        title: "វិធីសាស្រ្តសិក្សាដែលមានប្រសិទ្ធភាពសម្រាប់មធ្យមសិក្សា",
        description: "ការរៀនប្រកបដោយប្រព័ន្ធ និងការអនុវត្តន៍ជាក់ស្តែងជួយឲ្យសិស្សមានជោគជ័យ។",
        type: "article",
        topic: "Study Skills",
    },
    {
        title: "The Importance of English for Cambodian Teens",
        description: "Learning English opens opportunities for higher education and future careers.",
        type: "article",
        topic: "English",
    },
    {
        title: "ការរីកចម្រើននៃវិទ្យាសាស្ត្រនៅសាលាមធ្យមសិក្សា",
        description: "វិទ្យាសាស្ត្រ ជាគន្លងសំខាន់សម្រាប់ការអភិវឌ្ឍប្រទេស។",
        type: "article",
        topic: "Science",
    },
    {
        title: "How to Improve Study Habits in High School",
        description: "This post discusses practical strategies for students to improve their learning habits.",
        type: "tips",
        topic: "Study Skills",
    },
    {
        title: "តួនាទីរបស់គ្រូនៅក្នុងការអប់រំកម្ពុជា",
        description: "គ្រូមានតួនាទីសំខាន់ក្នុងការបណ្តុះបណ្តាល និងណែនាំសិស្សក្នុងមធ្យមសិក្សា។",
        type: "article",
        topic: "Education",
    },
    {
        title: "Effective Time Management for Students",
        description: "Managing time effectively helps students balance studies, hobbies, and exams.",
        type: "tips",
        topic: "Time Management",
    },
    {
        title: "ការគ្រប់គ្រងពេលវេលាដែលមានប្រសិទ្ធភាពសម្រាប់សិស្ស",
        description: "ការគ្រប់គ្រងពេលវេលាឱ្យមានប្រសិទ្ធភាពជួយសិស្សធ្វើតុល្យភាពរវាងការសិក្សា និងការសម្រាក។",
        type: "tips",
        topic: "Time Management",
    },
    {
        title: "Preparing for the Bac II Exam Successfully",
        description: "Preparing early for exams ensures better results and reduces stress.",
        type: "guide",
        topic: "Exam Preparation",
    },
    {
        title: "ការរៀបចំសម្រាប់ប្រឡង Bac II",
        description: "ការរៀបចំមុនពេលប្រឡងធ្វើឱ្យសិស្សទទួលបានលទ្ធផលល្អ និងកាត់បន្ថយសំពាធ។",
        type: "guide",
        topic: "Exam Preparation",
    },
    {
        title: "Overcoming Stress During High School",
        description: "Students face stress, but proper planning and breaks help overcome it.",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "ការកាត់បន្ថយសំពាធនៅក្នុងមធ្យមសិក្សា",
        description: "សិស្សជួបសំពាធ ប៉ុន្តែការធ្វើផែនការល្អ និងការសម្រាកជួយឱ្យកាត់បន្ថយវា។",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "Importance of Reading for Students",
        description: "Reading regularly enhances knowledge and critical thinking skills.",
        type: "article",
        topic: "Reading",
    },
    {
        title: "សារៈសំខាន់នៃការអានសម្រាប់សិស្ស",
        description: "ការអានជាប្រចាំបង្កើនចំណេះដឹង និងជំនាញគិតវិចារណញ្ញា។",
        type: "article",
        topic: "Reading",
    },
    {
        title: "Learning English as a Second Language",
        description: "English is essential for higher education and global opportunities.",
        type: "article",
        topic: "English",
    },
    {
        title: "ការសិក្សាភាសាអង់គ្លេសជាភាសាទីពីរ",
        description: "ការសិក្សាភាសាអង់គ្លេសមានសារៈសំខាន់សម្រាប់ការអប់រំខ្ពស់ និងឱកាសអន្តរជាតិ។",
        type: "article",
        topic: "English",
    },
    {
        title: "Exploring Career Options After High School",
        description: "Exploring career options early helps students make informed decisions.",
        type: "guide",
        topic: "Career",
    },
    {
        title: "ការស្វែងរកជម្រើសមុខវិជ្ជាផ្សេងៗបន្ទាប់ពីមធ្យមសិក្សា",
        description: "ការស្វែងរកជម្រើសមុខវិជ្ជាពីមុនជួយសិស្សធ្វើការសម្រេចចិត្តបានឆ្លាតវៃ។",
        type: "guide",
        topic: "Career",
    },
    {
        title: "Balancing Sports and Academics",
        description: "Students benefit from extracurricular activities, but academics must come first.",
        type: "tips",
        topic: "Balance",
    },
    {
        title: "តុល្យភាពរវាងកីឡា និងសិក្សា",
        description: "ការចូលរួមក្នុងសកម្មភាពក្រៅម៉ោងអាចជួយសិស្សបង្កើនជំនាញ ប៉ុន្តែការសិក្សាអាចមិនត្រូវអោយខកខាន។",
        type: "tips",
        topic: "Balance",
    },
    {
        title: "Using Technology to Learn Effectively",
        description: "Online platforms and educational apps can enhance learning experiences.",
        type: "tips",
        topic: "Technology",
    },
    {
        title: "ការប្រើបច្ចេកវិទ្យាដើម្បីសិក្សាបានប្រសើរ",
        description: "វេទិកាអនឡាញ និងកម្មវិធីអប់រំជួយសិស្សក្នុងការសិក្សាបានប្រសើរ។",
        type: "tips",
        topic: "Technology",
    },
    {
        title: "Group Study Tips for High School Students",
        description: "Studying with peers can increase understanding and motivation.",
        type: "tips",
        topic: "Group Study",
    },
    {
        title: "យុទ្ធសាស្រ្តរៀនជាក្រុមសម្រាប់សិស្សមធ្យមសិក្សា",
        description: "ការរៀនជាក្រុមជួយសិស្សបង្កើនការយល់ដឹង និងកម្លាំងចិត្ត។",
        type: "tips",
        topic: "Group Study",
    },
    {
        title: "Effective Note-Taking Strategies",
        description: "Taking organized notes improves memory retention and exam performance.",
        type: "tips",
        topic: "Note-Taking",
    },
    {
        title: "យុទ្ធសាស្រ្តកត់ចំណាំមានប្រសិទ្ធភាព",
        description: "ការកត់ចំណាំដោយច្បាស់អាចជួយបង្កើនការចងចាំ និងលទ្ធផលប្រឡង។",
        type: "tips",
        topic: "Note-Taking",
    },
    {
        title: "How to Stay Motivated in High School",
        description: "Set goals, reward yourself, and stay consistent to maintain motivation.",
        type: "tips",
        topic: "Motivation",
    },
    {
        title: "របៀបរកកម្លាំងចិត្តនៅក្នុងមធ្យមសិក្សា",
        description: "កំណត់គោលដៅ ផ្តល់រង្វាន់ខ្លួនឯង និងរក្សាទម្លាប់ល្អ។",
        type: "tips",
        topic: "Motivation",
    },
    {
        title: "The Role of Parents in Education",
        description: "Parental involvement is key to student success and discipline.",
        type: "article",
        topic: "Education",
    },
    {
        title: "តួនាទីរបស់មាតាបិតា ក្នុងការអប់រំ",
        description: "ការចូលរួមរបស់មាតាបិតាជាកត្តាសំខាន់សម្រាប់ភាពជោគជ័យរបស់សិស្ស។",
        type: "article",
        topic: "Education",
    },
    {
        title: "Tips for Improving Writing Skills",
        description: "Regular practice and reading widely improves essay writing.",
        type: "tips",
        topic: "Writing",
    },
    {
        title: "យុទ្ធសាស្រ្តបង្កើនជំនាញសរសេរ",
        description: "ការអនុវត្តជាប្រចាំ និងការអានជាច្រើនជួយបង្កើនជំនាញសរសេរ។",
        type: "tips",
        topic: "Writing",
    },
    {
        title: "Understanding Science Concepts Easily",
        description: "Hands-on experiments help students grasp scientific concepts better.",
        type: "tips",
        topic: "Science",
    },
    {
        title: "ការយល់ដឹងពីមុខវិជ្ជាវិទ្យាសាស្ត្រងាយៗ",
        description: "ការធ្វើពិសោធន៍ជាក់ស្តែងជួយសិស្សយល់បានល្អ។",
        type: "tips",
        topic: "Science",
    },
    {
        title: "Overcoming Procrastination",
        description: "Plan ahead, set small tasks, and eliminate distractions to finish work on time.",
        type: "tips",
        topic: "Productivity",
    },
    {
        title: "ការជៀសវាងការពន្យារពេល",
        description: "រៀបចំផែនការ កំណត់ភារកិច្ចតូចៗ និងបញ្ចេញការរំខាន។",
        type: "tips",
        topic: "Productivity",
    },
    {
        title: "How to Participate Actively in Class",
        description: "Ask questions, engage in discussions, and contribute ideas.",
        type: "tips",
        topic: "Class Participation",
    },
    {
        title: "របៀបចូលរួមសកម្មភាពថ្នាក់",
        description: "សួរពីចម្ងល់ ចូលរួមពិភាក្សា និងចែករំលែកគំនិត។",
        type: "tips",
        topic: "Class Participation",
    },
    {
        title: "Importance of Attendance",
        description: "Regular attendance ensures continuity in learning and understanding.",
        type: "article",
        topic: "Attendance",
    },
    {
        title: "សារៈសំខាន់នៃការចូលរៀន",
        description: "ការចូលរៀនជាប្រចាំធានាការបន្តការសិក្សា និងការយល់ដឹង។",
        type: "article",
        topic: "Attendance",
    },
    {
        title: "How to Prepare for Group Projects",
        description: "Divide tasks fairly, communicate well, and meet deadlines.",
        type: "guide",
        topic: "Group Projects",
    },
    {
        title: "របៀបរៀបចំគម្រោងក្រុម",
        description: "ចែកចំណែកភារកិច្ចយ៉ាងសមរម្យ ចាប់អារម្មណ៍ និងគោរពពេលកំណត់។",
        type: "guide",
        topic: "Group Projects",
    },
    {
        title: "Building Confidence in Public Speaking",
        description: "Practice, prepare, and stay calm to speak confidently in front of peers.",
        type: "tips",
        topic: "Public Speaking",
    },
    {
        title: "ការបង្កើនទំនុកចិត្តក្នុងការនិយាយសាធារណៈ",
        description: "អនុវត្ត រៀបចំ និងរក្សាស្ងប់ស្ងាត់។",
        type: "tips",
        topic: "Public Speaking",
    },
    {
        title: "Learning from Mistakes",
        description: "Mistakes are learning opportunities; analyze and improve.",
        type: "tips",
        topic: "Personal Growth",
    },
    {
        title: "ការរៀនពីកំហុស",
        description: "កំហុសជាឱកាសរៀន; វិភាគ និងកែលម្អ។",
        type: "tips",
        topic: "Personal Growth",
    },
    {
        title: "Effective Revision Techniques",
        description: "Use flashcards, summaries, and practice tests to revise efficiently.",
        type: "tips",
        topic: "Revision",
    },
    {
        title: "យុទ្ធសាស្រ្តពិនិត្យវិញមានប្រសិទ្ធភាព",
        description: "ប្រើកាតរំលឹក សេចក្តីសង្ខេប និងការប្រឡងសាកល្បង។",
        type: "tips",
        topic: "Revision",
    },
    {
        title: "Developing Critical Thinking Skills",
        description: "Question assumptions and analyze information critically.",
        type: "tips",
        topic: "Critical Thinking",
    },
    {
        title: "ការអភិវឌ្ឍជំនាញគិតវិចារណញ្ញា",
        description: "សួរពីការសន្មត់ និងវិភាគព័ត៌មានយ៉ាងម៉ត់ចត់។",
        type: "tips",
        topic: "Critical Thinking",
    },
    {
        title: "How to Write a Good Essay",
        description: "Plan structure, support arguments with examples, and proofread.",
        type: "guide",
        topic: "Writing",
    },
    {
        title: "របៀបសរសេរអត្ថបទល្អ",
        description: "រៀបចំរចនាសម្ព័ន្ធ គាំទ្រពត៌មានដោយឧទាហរណ៍ និងពិនិត្យមើលម្ដងទៀត។",
        type: "guide",
        topic: "Writing",
    },
    {
        title: "Time Management for Exam Weeks",
        description: "Prioritize subjects, avoid distractions, and create a study timetable.",
        type: "tips",
        topic: "Time Management",
    },
    {
        title: "ការគ្រប់គ្រងពេលវេលាសម្រាប់សប្តាហ៍ប្រឡង",
        description: "អាទិភាពផ្ដល់ឱ្យមុខវិជ្ជា ចៀសវាងការរំខាន និងបង្កើតកាលវិភាគសិក្សា។",
        type: "tips",
        topic: "Time Management",
    },
    {
        title: "Using Library Resources Effectively",
        description: "Research books, journals, and online databases for better learning.",
        type: "tips",
        topic: "Library",
    },
    {
        title: "ការប្រើប្រាស់ធនធានបណ្ណាល័យមានប្រសិទ្ធភាព",
        description: "ស្រាវជ្រាវសៀវភៅ អត្ថបទ និងមូលដ្ឋានទិន្នន័យអនឡាញ។",
        type: "tips",
        topic: "Library",
    },
    {
        title: "Tips for Better Memory Retention",
        description: "Use mnemonics, repetition, and active recall to remember facts.",
        type: "tips",
        topic: "Memory",
    },
    {
        title: "យុទ្ធសាស្រ្តចងចាំបានល្អ",
        description: "ប្រើអត្ថបទជំនួញ ការអនុវត្តស្ទាត់ និងការចងចាំសកម្ម។",
        type: "tips",
        topic: "Memory",
    },
    {
        title: "How to Stay Healthy During School",
        description: "Balanced diet, exercise, and enough sleep support learning.",
        type: "tips",
        topic: "Health",
    },
    {
        title: "របៀបរក្សាសុខភាពនៅក្នុងសាលា",
        description: "អាហារតុល្យភាព ការអវត្តមាន និងការគេងគ្រប់គ្រាន់។",
        type: "tips",
        topic: "Health",
    },
    {
        title: "The Value of Teamwork in School Projects",
        description: "Collaborating with peers develops skills and achieves better results.",
        type: "article",
        topic: "Teamwork",
    },
    {
        title: "តម្លៃនៃការធ្វើការជាក្រុមក្នុងគម្រោងសាលា",
        description: "ការរួមគ្នាជាមួយមិត្តរួមសិក្សាអភិវឌ្ឍជំនាញ និងទទួលបានលទ្ធផលល្អ។",
        type: "article",
        topic: "Teamwork",
    },
    {
        title: "How to Take Effective Breaks",
        description: "Short breaks between study sessions improve focus and productivity.",
        type: "tips",
        topic: "Productivity",
    },
    {
        title: "របៀបសម្រាកមានប្រសិទ្ធភាព",
        description: "សម្រាកខ្លីរវាងសម័យសិក្សាជួយបង្កើនការផ្ដោតអារម្មណ៍។",
        type: "tips",
        topic: "Productivity",
    },
    {
        title: "Importance of Asking Questions in Class",
        description: "Questions clarify doubts and deepen understanding.",
        type: "tips",
        topic: "Class Participation",
    },
    {
        title: "សារៈសំខាន់នៃការសួរពីចម្ងល់ក្នុងថ្នាក់",
        description: "សំនួរជួយបំភ្លឺការភាន់ច្រឡំ និងជំរុញការយល់ដឹង។",
        type: "tips",
        topic: "Class Participation",
    },
    {
        title: "How to Balance Homework and Hobbies",
        description: "Allocate time for both to maintain a healthy lifestyle.",
        type: "tips",
        topic: "Balance",
    },
    {
        title: "របៀបធ្វើតុល្យភាពរវាងការងារផ្ទះ និងសប្បាយរីករាយ",
        description: "ចែកចំណែកពេលវេលាដើម្បីទទួលបានជីវិតមានសុខភាពល្អ។",
        type: "tips",
        topic: "Balance",
    },
    {
        title: "Overcoming Exam Anxiety",
        description: "Relaxation techniques and practice help reduce stress before exams.",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "ការឆ្លងកាត់ការភ័យខ្លាចប្រឡង",
        description: "យុទ្ធសាស្រ្តសំរាក និងការអនុវត្តជួយកាត់បន្ថយសំពាធ។",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "Using Mind Maps for Learning",
        description: "Visual maps organize information and enhance memory.",
        type: "tips",
        topic: "Study Skills",
    },
    {
        title: "ការប្រើផែនទីចិត្តសម្រាប់ការសិក្សា",
        description: "ផែនទីជាចក្ខុវិស័យរៀបចំព័ត៌មាន និងបង្កើនការចងចាំ។",
        type: "tips",
        topic: "Study Skills",
    },
    {
        title: "How to Improve Concentration",
        description: "Minimize distractions, take notes, and set small goals.",
        type: "tips",
        topic: "Concentration",
    },
    {
        title: "របៀបបង្កើនការផ្ដោតអារម្មណ៍",
        description: "កាត់បន្ថយការរំខាន កត់ចំណាំ និងកំណត់គោលដៅតូចៗ។",
        type: "tips",
        topic: "Concentration",
    },
    {
        title: "The Role of Extracurricular Activities",
        description: "Clubs and sports develop skills beyond academics.",
        type: "article",
        topic: "Extracurricular",
    },
    {
        title: "តួនាទីនៃសកម្មភាពក្រៅម៉ោង",
        description: "ក្លឹប និងកីឡាអភិវឌ្ឍជំនាញលើសការសិក្សា។",
        type: "article",
        topic: "Extracurricular",
    },
    {
        title: "Learning Through Educational Games",
        description: "Interactive games make learning engaging and memorable.",
        type: "tips",
        topic: "Educational Games",
    },
    {
        title: "ការរៀនតាមរបៀបលេងហ្គេមអប់រំ",
        description: "ហ្គេមអន្តរកម្មធ្វើឲ្យការសិក្សារីករាយ និងចងចាំបានល្អ។",
        type: "tips",
        topic: "Educational Games",
    },
    {
        title: "How to Develop Self-Discipline",
        description: "Set rules for yourself and stick to routines for better performance.",
        type: "tips",
        topic: "Self-Discipline",
    },
    {
        title: "របៀបអភិវឌ្ឍវិន័យខ្លួនឯង",
        description: "កំណត់ច្បាប់សម្រាប់ខ្លួនឯង និងអនុវត្តប្រព័ន្ធតាមរយៈទម្លាប់។",
        type: "tips",
        topic: "Self-Discipline",
    },
    {
        title: "Preparing Notes Before Classes",
        description: "Pre-reading and preparing questions improves class participation.",
        type: "tips",
        topic: "Note-Taking",
    },
    {
        title: "ការរៀបចំកំណត់ចំណាំមុនថ្នាក់",
        description: "អានមុន និងរៀបចំសំនួរជួយការចូលរួមក្នុងថ្នាក់។",
        type: "tips",
        topic: "Note-Taking",
    },
    {
        title: "Benefits of Peer Tutoring",
        description: "Teaching others reinforces your own understanding and helps classmates.",
        type: "article",
        topic: "Peer Tutoring",
    },
    {
        title: "អត្ថប្រយោជន៍នៃការជួយគ្នាសិក្សាជាមិត្ត",
        description: "បង្រៀនអ្នកផ្សេងជួយបង្កើនការយល់ដឹងរបស់ខ្លួន និងជំនួយមិត្ត។",
        type: "article",
        topic: "Peer Tutoring",
    },
    {
        title: "How to Use Past Papers Effectively",
        description: "Practice with previous exams improves confidence and exam skills.",
        type: "tips",
        topic: "Exam Preparation",
    },
    {
        title: "របៀបប្រើប្រាស់សំណួរប្រឡងមុន",
        description: "ការអនុវត្តជាមួយសំណួរប្រឡងពីមុនបង្កើនទំនុកចិត្ត និងជំនាញប្រឡង។",
        type: "tips",
        topic: "Exam Preparation",
    },
    {
        title: "Setting Realistic Academic Goals",
        description: "Break large goals into small achievable steps for success.",
        type: "tips",
        topic: "Goal Setting",
    },
    {
        title: "កំណត់គោលដៅសិក្សាជាក់ស្តែង",
        description: "បំបែកគោលដៅធំទៅជាជំហានតូចៗដែលអាចសម្រេចបាន។",
        type: "tips",
        topic: "Goal Setting",
    },
    {
        title: "How to Improve Science Lab Skills",
        description: "Follow procedures carefully and take accurate measurements.",
        type: "tips",
        topic: "Science",
    },
    {
        title: "របៀបបង្កើនជំនាញមន្ទីរពិសោធន៍វិទ្យាសាស្ត្រ",
        description: "អនុវត្តន៍តាមដំណើរការយ៉ាងម៉ត់ចត់ និងវាស់ត្រឹមត្រូវ។",
        type: "tips",
        topic: "Science",
    },
    {
        title: "The Importance of Asking for Help",
        description: "Seeking assistance from teachers or peers strengthens understanding.",
        type: "tips",
        topic: "Help Seeking",
    },
    {
        title: "សារៈសំខាន់នៃការស្នើសុំជំនួយ",
        description: "ស្នើសុំជំនួយពីគ្រូ ឬមិត្តជួយបង្កើនការយល់ដឹង។",
        type: "tips",
        topic: "Help Seeking",
    },
    {
        title: "How to Make Study Plans",
        description: "Plan weekly schedules and set daily tasks for organized learning.",
        type: "tips",
        topic: "Study Skills",
    },
    {
        title: "របៀបរៀបចំផែនការសិក្សា",
        description: "រៀបចំកាលវិភាគប្រចាំសប្តាហ៍ និងកំណត់ភារកិច្ចប្រចាំថ្ងៃ។",
        type: "tips",
        topic: "Study Skills",
    },
    {
        title: "Using Rewards to Stay Motivated",
        description: "Reward yourself after completing tasks to maintain motivation.",
        type: "tips",
        topic: "Motivation",
    },
    {
        title: "ការប្រើរង្វាន់ដើម្បីរកកម្លាំងចិត្ត",
        description: "ផ្តល់រង្វាន់ខ្លួនឯងបន្ទាប់ពីបញ្ចប់ភារកិច្ច។",
        type: "tips",
        topic: "Motivation",
    },
    {
        title: "How to Take Care of Mental Health",
        description: "Talk to friends, practice relaxation, and maintain hobbies.",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "របៀបថែរក្សាសុខភាពផ្លូវចិត្ត",
        description: "និយាយជាមួយមិត្ត ស្វែងយល់ការសម្រាក និងរក្សាសប្បាយ។",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "Effective Revision Before Exams",
        description: "Use summaries, practice tests, and group discussions to revise effectively.",
        type: "tips",
        topic: "Revision",
    },
    {
        title: "ការពិនិត្យវិញប្រសិទ្ធភាពមុនប្រឡង",
        description: "ប្រើសេចក្តីសង្ខេប សាកល្បង និងពិភាក្សាជាក្រុម។",
        type: "tips",
        topic: "Revision",
    },
    {
        title: "How to Manage Stress During Exams",
        description: "Exercise, sleep well, and stay positive to handle stress.",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "របៀបគ្រប់គ្រងសំពាធនៅពេលប្រឡង",
        description: "ហាត់ប្រាណ គេងគ្រប់គ្រាន់ និងរក្សាមនោសញ្ចេតនា។",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "Tips for Successful Group Discussions",
        description: "Listen actively, respect opinions, and contribute meaningfully.",
        type: "tips",
        topic: "Group Study",
    },
    {
        title: "យុទ្ធសាស្រ្តសម្រាប់ការពិភាក្សាក្រុមជោគជ័យ",
        description: "ស្តាប់យ៉ាងសកម្ម គោរពមតិ និងចូលរួមយ៉ាងមានន័យ។",
        type: "tips",
        topic: "Group Study",
    },
    {
        title: "The Role of Libraries in Learning",
        description: "Libraries provide access to resources that enhance knowledge.",
        type: "article",
        topic: "Library",
    },
    {
        title: "តួនាទីនៃបណ្ណាល័យក្នុងការសិក្សា",
        description: "បណ្ណាល័យផ្តល់ឱកាសចូលដំណើរការទិន្នន័យដែលបង្កើនចំណេះដឹង។",
        type: "article",
        topic: "Library",
    },
    {
        title: "How to Stay Focused During Study Sessions",
        description: "Avoid distractions and break tasks into smaller steps.",
        type: "tips",
        topic: "Concentration",
    },
    {
        title: "របៀបផ្ដោតអារម្មណ៍ពេលសិក្សា",
        description: "ចៀសវាងការរំខាន និងបំបែកភារកិច្ចទៅជាជំហានតូចៗ។",
        type: "tips",
        topic: "Concentration",
    },
    {
        title: "Developing Leadership Skills in School",
        description: "Participate in clubs and volunteer opportunities to lead.",
        type: "tips",
        topic: "Leadership",
    },
    {
        title: "ការអភិវឌ្ឍជំនាញភាពដឹកនាំនៅសាលា",
        description: "ចូលរួមក្នុងក្លឹប និងសកម្មភាពស្ម័គ្រចិត្តដើម្បីដឹកនាំ។",
        type: "tips",
        topic: "Leadership",
    },
    {
        title: "How to Use Educational Apps Effectively",
        description: "Select apps that align with learning goals and practice regularly.",
        type: "tips",
        topic: "Technology",
    },
    {
        title: "របៀបប្រើកម្មវិធីអប់រំមានប្រសិទ្ធភាព",
        description: "ជ្រើសកម្មវិធីដែលសមស្រប និងអនុវត្តជាប្រចាំ។",
        type: "tips",
        topic: "Technology",
    },
    {
        title: "Tips for Collaborative Projects",
        description: "Communicate clearly, share responsibilities, and meet deadlines.",
        type: "tips",
        topic: "Collaboration",
    },
    {
        title: "យុទ្ធសាស្រ្តសម្រាប់គម្រោងសហការ",
        description: "ផ្សព្វផ្សាយយ៉ាងច្បាស់ ចែកចំណែកភារកិច្ច និងគោរពពេលកំណត់។",
        type: "tips",
        topic: "Collaboration",
    },
    {
        title: "How to Write Clear Notes",
        description: "Use headings, bullet points, and diagrams for clarity.",
        type: "tips",
        topic: "Note-Taking",
    },
    {
        title: "របៀបសរសេរកំណត់ចំណាំច្បាស់",
        description: "ប្រើចំណងជើង ចំណុច និងគំនូរ។",
        type: "tips",
        topic: "Note-Taking",
    },
    {
        title: "Understanding History Better",
        description: "Relate events to current issues to improve understanding.",
        type: "tips",
        topic: "History",
    },
    {
        title: "ការយល់ដឹងពីប្រវត្តិសាស្ត្រល្អប្រសើរ",
        description: "ភ្ជាប់ព្រឹត្តិការណ៍ទៅនឹងបញ្ហាបច្ចុប្បន្ន។",
        type: "tips",
        topic: "History",
    },
    {
        title: "How to Improve Listening Skills",
        description: "Practice active listening and summarize what you hear.",
        type: "tips",
        topic: "Listening",
    },
    {
        title: "របៀបបង្កើនជំនាញស្តាប់",
        description: "អនុវត្តការស្តាប់សកម្ម និងសង្ខេបអ្វីដែលបានស្តាប់។",
        type: "tips",
        topic: "Listening",
    },
    {
        title: "Using Peer Feedback Effectively",
        description: "Give and receive constructive feedback to improve learning.",
        type: "tips",
        topic: "Peer Feedback",
    },
    {
        title: "ការប្រើមតិយោបល់មិត្តមានប្រសិទ្ធភាព",
        description: "ផ្តល់ និងទទួលមតិយោបល់សម្រាប់កែលម្អការសិក្សា។",
        type: "tips",
        topic: "Peer Feedback",
    },
    {
        title: "Tips for Writing Reports",
        description: "Structure clearly, support with data, and proofread carefully.",
        type: "tips",
        topic: "Writing",
    },
    {
        title: "យុទ្ធសាស្រ្តសរសេររាយការណ៍",
        description: "រៀបចំយ៉ាងច្បាស់ គាំទ្រដោយទិន្នន័យ និងពិនិត្យមើល។",
        type: "tips",
        topic: "Writing",
    },
    {
        title: "How to Stay Organized in High School",
        description: "Use planners, folders, and checklists to manage tasks.",
        type: "tips",
        topic: "Organization",
    },
    {
        title: "របៀបរៀបចំសម្រាប់មធ្យមសិក្សា",
        description: "ប្រើកាលវិភាគ ប័ណ្ណ និងបញ្ជីត្រួតពិនិត្យភារកិច្ច។",
        type: "tips",
        topic: "Organization",
    },
    {
        title: "Effective Strategies for Memorization",
        description: "Use repetition, visual aids, and associations to remember facts.",
        type: "tips",
        topic: "Memory",
    },
    {
        title: "យុទ្ធសាស្រ្តមានប្រសិទ្ធភាពសម្រាប់ចងចាំ",
        description: "ប្រើការអនុវត្ត សម្រង់ និងការតភ្ជាប់។",
        type: "tips",
        topic: "Memory",
    },
    {
        title: "How to Handle Peer Pressure",
        description: "Stay confident, choose friends wisely, and follow your values.",
        type: "tips",
        topic: "Peer Pressure",
    },
    {
        title: "របៀបដោះស្រាយសំពាធមិត្តភក្តិ",
        description: "រក្សាទំនុកចិត្ត ជ្រើសមិត្តឆ្លាតវៃ និងអនុវត្តតាមតម្លៃខ្លួន។",
        type: "tips",
        topic: "Peer Pressure",
    },
    {
        title: "Preparing for Oral Exams",
        description: "Practice speaking clearly, anticipate questions, and stay calm.",
        type: "tips",
        topic: "Exam Preparation",
    },
    {
        title: "ការរៀបចំសម្រាប់ប្រឡងមាត់",
        description: "ហាត់និយាយច្បាស់ ទស្សនាសំនួរ និងរក្សាស្ងប់ស្ងាត់។",
        type: "tips",
        topic: "Exam Preparation",
    },
    {
        title: "How to Set Study Priorities",
        description: "Identify difficult subjects first and allocate more time accordingly.",
        type: "tips",
        topic: "Study Skills",
    },
    {
        title: "របៀបកំណត់អាទិភាពសិក្សា",
        description: "កំណត់មុខវិជ្ជាលំបាកជាមុន និងចំណាយពេលវេលាឱ្យសមស្រប។",
        type: "tips",
        topic: "Study Skills",
    },
    {
        title: "Benefits of Reading Aloud",
        description: "Reading aloud improves pronunciation, comprehension, and retention.",
        type: "tips",
        topic: "Reading",
    },
    {
        title: "អត្ថប្រយោជន៍នៃការអានឡើងសម្លេង",
        description: "អានឡើងសម្លេងជួយការបញ្ចេញសូរ វាយតម្លៃ និងចងចាំបានល្អ។",
        type: "tips",
        topic: "Reading",
    },
    {
        title: "Using Educational Videos",
        description: "Visual content helps explain complex topics clearly.",
        type: "tips",
        topic: "Technology",
    },
    {
        title: "ការប្រើវីដេអូអប់រំ",
        description: "មាតិកាទិដ្ឋភាពជួយបង្ហាញប្រធានបទស្មុគស្មាញយ៉ាងច្បាស់។",
        type: "tips",
        topic: "Technology",
    },
    {
        title: "How to Avoid Burnout in High School",
        description: "Take breaks, pursue hobbies, and maintain a balanced schedule.",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "របៀបជៀសវាងការធុញទ្រាន់នៅមធ្យមសិក្សា",
        description: "សម្រាក ស្វែងរកសប្បាយ និងរក្សាទម្លាប់តុល្យភាព។",
        type: "tips",
        topic: "Mental Health",
    },
    {
        title: "Tips for Better Participation in Class",
        description: "Listen carefully, contribute ideas, and stay engaged.",
        type: "tips",
        topic: "Class Participation",
    },
    {
        title: "យុទ្ធសាស្រ្តសម្រាប់ចូលរួមល្អក្នុងថ្នាក់",
        description: "ស្តាប់យ៉ាងប្រុងប្រយ័ត្ន ចែករំលែកគំនិត និងចូលរួមសកម្ម។",
        type: "tips",
        topic: "Class Participation",
    },
    {
        title: "How to Use Flashcards for Revision",
        description: "Flashcards help with quick review and memorization.",
        type: "tips",
        topic: "Revision",
    },
    {
        title: "របៀបប្រើកាតរំលឹកសម្រាប់ពិនិត្យវិញ",
        description: "កាតរំលឹកជួយពិនិត្យយ៉ាងរហ័ស និងចងចាំ។",
        type: "tips",
        topic: "Revision",
    },
    {
        title: "Developing Problem-Solving Skills",
        description: "Practice logical thinking and analyze situations carefully.",
        type: "tips",
        topic: "Problem Solving",
    },
    {
        title: "ការអភិវឌ្ឍជំនាញដោះស្រាយបញ្ហា",
        description: "អនុវត្តការគិតយ៉ាងត្រឹមត្រូវ និងវិភាគស្ថានភាព។",
        type: "tips",
        topic: "Problem Solving",
    },
];

export const mockComments = [
	"This post really helped me understand the challenges in high school! 📚💡",
	"អត្ថបទនេះមានប្រយោជន៍ខ្លាំងសម្រាប់សិស្សនៅមធ្យមសិក្សា 🎓✨",
	"I love the tips about balancing sports and studies ⚽📖",
	"ខ្ញុំចូលចិត្តផ្នែកដែលនិយាយអំពីការគ្រប់គ្រងពេលវេលា ⏰📝",
	"Very helpful advice on managing stress during exams 😌📝",
	"ខ្ញុំពិតជាស្វែងយល់ពីយុទ្ធសាស្រ្តពិនិត្យវិញនេះ 📖✨",
	"These note-taking tips are awesome! 📝👍",
	"ខ្ញុំនឹងអនុវត្តវិធីសាស្រ្តកត់ចំណាំនេះពិតណាស់ 📚💪",
	"I didn’t know educational apps could be so useful! 📱💡",
	"ខ្ញុំយល់ព្រម! ការអនុវត្តប្រើកម្មវិធីអប់រំជួយសិក្សាអោយបានល្អ 🎓😊",
	"Really love how this article explains exam preparation ✏️🧠",
	"ការរៀបចំប្រឡងតាមអត្ថបទនេះជួយខ្ញុំយល់បានច្បាស់ 📖💯",
	"Reading habits are so important! 📚❤️",
	"អត្ថបទនេះជំរុញឱ្យខ្ញុំអានជាប្រចាំ 🎓✨",
	"I’ll try these group study strategies with my friends 👩‍🎓👨‍🎓",
	"យុទ្ធសាស្រ្តរៀនជាក្រុមនេះពិតជាមានប្រយោជន៍ 💡📖",
	"Thanks for explaining the importance of mental health during exams 🧘‍♂️💙",
	"អត្ថបទនេះបង្ហាញពីសារៈសំខាន់នៃសុខភាពផ្លូវចិត្ត 🧘‍♀️✨",
	"Love the practical examples provided in this post 👏📚",
	"ខ្ញុំចូលចិត្តឧទាហរណ៍ជាក់ស្តែងក្នុងអត្ថបទនេះ 🎓💡",
];

export const mockReplies = [
	"Absolutely! These tips are so practical 🙌",
	"Thanks for sharing! I’ll try them in my next exam 😄",
	"Agreed! Very insightful 💯",
	"ពិតណាស់! វាជួយខ្ញុំរៀនប្រកបដោយប្រព័ន្ធ 📖",
	"ខ្ញុំសូមអរគុណសម្រាប់ការចែករំលែកនេះ 😊",
	"អត្ថបទនេះមានប្រយោជន៍ណាស់! 🎓✨",
	"Same here! Maintaining balance is so important 👍",
	"Great advice, I’m going to follow it 💪",
	"I’ll share it with my classmates too 😄",
	"យុទ្ធសាស្រ្តនេះពិតជាមានប្រយោជន៍ 😄",
	"ខ្ញុំនឹងអនុវត្តវាឱ្យបានត្រឹមត្រូវ 💯",
	"សូមអរគុណច្រើន! 📚✨",
	"I will try these strategies next exam! ✏️📖",
	"Super helpful, thanks! 🌟",
	"Definitely useful tips! 👍",
	"ខ្ញុំបានរៀនច្រើនពីអត្ថបទនេះ 🎓",
	"វាជួយខ្ញុំបង្កើនការយល់ដឹង 💡",
	"មិនអាចជឿបានថាវាមានប្រយោជន៍បានច្រើននេះ 😄",
	"Can’t wait to use these note-taking methods 📝✨",
	"This will make studying so much easier 😄",
	"I’m going to share with my study group 👍",
	"ពិតណាស់! វាជួយខ្ញុំចងចាំបានល្អ 📚",
	"ខ្ញុំស្វែងយល់ពីវាច្រើន 👍",
	"ខ្ញុំសូមអរគុណច្រើន! 🎓",
	"I’m downloading these educational apps now! 📱😊",
	"Thanks for the recommendation 💡",
	"These apps seem really fun 😄📚",
	"វាពិតជាមានប្រយោជន៍ខ្លាំង 🎓",
	"ខ្ញុំនឹងអនុវត្តវាឱ្យបានត្រឹមត្រូវ 💯",
	"អត្ថបទនេះពិតជាជួយខ្ញុំបានច្រើន 😄",
	"Great advice for exam prep! ✏️💡",
	"I’ll start using these tips today 📖👍",
	"Thanks! This is super helpful 😊",
	"ការរៀបចំប្រឡងតាមអត្ថបទនេះជួយខ្ញុំយល់បានច្បាស់ 📖💯",
	"ខ្ញុំនឹងអនុវត្តវា 💪",
	"ពិតជាមានប្រយោជន៍ណាស់! 🎓",
	"Reading habits are life-changing! 📚❤️",
	"I’m going to read more starting today ✨",
	"អត្ថបទនេះជំរុញខ្ញុំបានច្រើន 🎓📖",
	"I’ll try these group study strategies with my friends 👩‍🎓👨‍🎓",
	"Sounds fun! We’ll start this week 💪",
	"Great idea! Teamwork helps a lot 😄",
	"Thanks for explaining the importance of mental health 🧘‍♂️💙",
	"Very important reminder 😌",
	"ខ្ញុំយល់ព្រម! វាជួយខ្ញុំរក្សាសុខភាពផ្លូវចិត្ត 🧘‍♀️✨",
	"Love the practical examples shared 👏📚",
	"ខ្ញុំចូលចិត្តឧទាហរណ៍ជាក់ស្តែងក្នុងអត្ថបទនេះ 🎓💡",
];

export const mockExercises = [
	{
		duration: 120,
		title: "Algebra Practice",
		description: "Solve linear equations and inequalities.",
		subject: "Math",
		grade: "10",
	},
	{
		duration: 90,
		title: "Newton's Laws",
		description: "Answer conceptual and calculation questions about Newton's laws of motion.",
		subject: "Physics",
		grade: "10",
	},
	{
		duration: 90,
		title: "Balancing Chemical Equations",
		description: "Balance the given chemical reactions.",
		subject: "Chemistry",
		grade: "10",
	},
	{
		duration: 90,
		title: "Cell Structure",
		description: "Label and describe the functions of cell organelles.",
		subject: "Biology",
		grade: "10",
	},
	{
		duration: 120,
		title: "Quadratic Equations",
		description: "Solve quadratic equations by factoring and using the quadratic formula.",
		subject: "Math",
		grade: "10",
	},
	{
		duration: 90,
		title: "Work and Energy",
		description: "Calculate work done and energy transformations in physical systems.",
		subject: "Physics",
		grade: "10",
	},
	{
		duration: 90,
		title: "Periodic Table",
		description: "Identify elements and groups on the periodic table.",
		subject: "Chemistry",
		grade: "10",
	},
	{
		duration: 90,
		title: "Photosynthesis",
		description: "Explain the process and importance of photosynthesis.",
		subject: "Biology",
		grade: "10",
	},
	{
		duration: 120,
		title: "Geometry Problems",
		description: "Solve problems involving triangles, circles, and polygons.",
		subject: "Math",
		grade: "10",
	},
	{
		duration: 90,
		title: "Waves and Sound",
		description: "Answer questions about wave properties and sound.",
		subject: "Physics",
		grade: "10",
	},
	{
		duration: 90,
		title: "Acids and Bases",
		description: "Classify substances as acids or bases and explain their properties.",
		subject: "Chemistry",
		grade: "10",
	},
	{
		duration: 90,
		title: "Genetics Basics",
		description: "Solve simple genetics problems using Punnett squares.",
		subject: "Biology",
		grade: "10",
	},
	{
		duration: 120,
		title: "Statistics and Probability",
		description: "Calculate mean, median, mode, and probability of events.",
		subject: "Math",
		grade: "10",
	},
	{
		duration: 90,
		title: "Electricity and Circuits",
		description: "Draw and analyze simple electric circuits.",
		subject: "Physics",
		grade: "10",
	},
	{
		duration: 90,
		title: "Chemical Bonding",
		description: "Describe ionic and covalent bonding with examples.",
		subject: "Chemistry",
		grade: "10",
	},
	{
		duration: 90,
		title: "Human Body Systems",
		description: "Identify and describe major human body systems.",
		subject: "Biology",
		grade: "10",
	},
	{
		duration: 120,
		title: "Trigonometry Basics",
		description: "Solve problems using sine, cosine, and tangent ratios.",
		subject: "Math",
		grade: "10",
	},
	{
		duration: 90,
		title: "Light and Optics",
		description: "Explain reflection, refraction, and lens behavior.",
		subject: "Physics",
		grade: "10",
	},
	{
		duration: 90,
		title: "States of Matter",
		description: "Describe properties and changes of solids, liquids, and gases.",
		subject: "Chemistry",
		grade: "10",
	},
	{
		duration: 90,
		title: "Ecology and Environment",
		description: "Discuss ecosystems, food chains, and environmental issues.",
		subject: "Biology",
		grade: "10",
	},
];

export const mockQuestions = [
	// 1. Algebra Practice
	{
		exerciseId: 1,
		title: "Solve: 2x + 5 = 15",
		questionType: "multiple_choice",
		section: "Linear Equations",
		imageUrl: "",
	},
	{
		exerciseId: 1,
		title: "Solve: 3x - 7 = 11",
		questionType: "multiple_choice",
		section: "Linear Equations",
		imageUrl: "",
	},
	{
		exerciseId: 1,
		title: "Solve inequality: 2x + 3 < 9",
		questionType: "multiple_choice",
		section: "Inequalities",
		imageUrl: "",
	},
	{
		exerciseId: 1,
		title: "Graph the solution of x > 4",
		questionType: "multiple_choice",
		section: "Inequalities",
		imageUrl: "https://example.com/graph.jpg",
	},
	{
		exerciseId: 1,
		title: "Solve simultaneous equations: 2x + y = 10, x - y = 2",
		questionType: "multiple_choice",
		section: "Simultaneous Equations",
		imageUrl: "",
	},

	// 2. Newton's Laws
	{
		exerciseId: 2,
		title: "State Newton's First Law",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 2,
		title: "What force is required to accelerate 2kg at 3 m/s²?",
		questionType: "multiple_choice",
		section: "Calculations",
		imageUrl: "",
	},
	{
		exerciseId: 2,
		title: "Which law explains action-reaction forces?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 2,
		title: "A 10N force acts on 5kg, find acceleration",
		questionType: "multiple_choice",
		section: "Calculations",
		imageUrl: "",
	},
	{
		exerciseId: 2,
		title: "Example of Newton’s Third Law in real life",
		questionType: "multiple_choice",
		section: "Applications",
		imageUrl: "",
	},

	// 3. Balancing Chemical Equations
	{
		exerciseId: 3,
		title: "Balance: H₂ + O₂ → H₂O",
		questionType: "multiple_choice",
		section: "Basic Equations",
		imageUrl: "",
	},
	{
		exerciseId: 3,
		title: "Balance: Na + Cl₂ → NaCl",
		questionType: "multiple_choice",
		section: "Basic Equations",
		imageUrl: "",
	},
	{
		exerciseId: 3,
		title: "Balance: Fe + O₂ → Fe₂O₃",
		questionType: "multiple_choice",
		section: "Intermediate",
		imageUrl: "",
	},
	{
		exerciseId: 3,
		title: "Balance: N₂ + H₂ → NH₃",
		questionType: "multiple_choice",
		section: "Intermediate",
		imageUrl: "",
	},
	{
		exerciseId: 3,
		title: "Balance: C₃H₈ + O₂ → CO₂ + H₂O",
		questionType: "multiple_choice",
		section: "Combustion",
		imageUrl: "",
	},

	// 4. Cell Structure
	{
		exerciseId: 4,
		title: "Identify the nucleus in a cell diagram",
		questionType: "multiple_choice",
		section: "Cell Organelles",
		imageUrl: "https://example.com/cell.jpg",
	},
	{
		exerciseId: 4,
		title: "Which organelle is the powerhouse of the cell?",
		questionType: "multiple_choice",
		section: "Cell Organelles",
		imageUrl: "",
	},
	{
		exerciseId: 4,
		title: "Function of ribosomes?",
		questionType: "multiple_choice",
		section: "Cell Organelles",
		imageUrl: "",
	},
	{
		exerciseId: 4,
		title: "Difference between plant and animal cells?",
		questionType: "multiple_choice",
		section: "Comparison",
		imageUrl: "",
	},
	{
		exerciseId: 4,
		title: "What is the function of the cell membrane?",
		questionType: "multiple_choice",
		section: "Cell Organelles",
		imageUrl: "",
	},

	// 5. Quadratic Equations
	{
		exerciseId: 5,
		title: "Solve: x² - 5x + 6 = 0",
		questionType: "multiple_choice",
		section: "Factoring",
		imageUrl: "",
	},
	{
		exerciseId: 5,
		title: "Solve using quadratic formula: x² + 4x + 4 = 0",
		questionType: "multiple_choice",
		section: "Quadratic Formula",
		imageUrl: "",
	},
	{
		exerciseId: 5,
		title: "Discriminant of x² + 2x + 5 = 0?",
		questionType: "multiple_choice",
		section: "Theory",
		imageUrl: "",
	},
	{
		exerciseId: 5,
		title: "Nature of roots when discriminant < 0?",
		questionType: "multiple_choice",
		section: "Theory",
		imageUrl: "",
	},
	{
		exerciseId: 5,
		title: "Solve: 2x² - 8x = 0",
		questionType: "multiple_choice",
		section: "Factoring",
		imageUrl: "",
	},

	// 6. Work and Energy
	{
		exerciseId: 6,
		title: "Define work in physics",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 6,
		title: "Work done when force 10N moves 5m?",
		questionType: "multiple_choice",
		section: "Calculations",
		imageUrl: "",
	},
	{
		exerciseId: 6,
		title: "Kinetic energy of 2kg at 3m/s?",
		questionType: "multiple_choice",
		section: "Energy",
		imageUrl: "",
	},
	{
		exerciseId: 6,
		title: "Potential energy formula?",
		questionType: "multiple_choice",
		section: "Energy",
		imageUrl: "",
	},
	{
		exerciseId: 6,
		title: "Example of energy transformation",
		questionType: "multiple_choice",
		section: "Applications",
		imageUrl: "",
	},

	// 7. Periodic Table
	{
		exerciseId: 7,
		title: "Element with atomic number 1?",
		questionType: "multiple_choice",
		section: "Basics",
		imageUrl: "",
	},
	{
		exerciseId: 7,
		title: "Group of noble gases?",
		questionType: "multiple_choice",
		section: "Groups",
		imageUrl: "",
	},
	{
		exerciseId: 7,
		title: "Symbol of sodium?",
		questionType: "multiple_choice",
		section: "Basics",
		imageUrl: "",
	},
	{
		exerciseId: 7,
		title: "Metals are found in which part of table?",
		questionType: "multiple_choice",
		section: "Classification",
		imageUrl: "",
	},
	{
		exerciseId: 7,
		title: "Periodic law states elements are arranged by?",
		questionType: "multiple_choice",
		section: "Theory",
		imageUrl: "",
	},

	// 8. Photosynthesis
	{
		exerciseId: 8,
		title: "Which organelle performs photosynthesis?",
		questionType: "multiple_choice",
		section: "Basics",
		imageUrl: "",
	},
	{
		exerciseId: 8,
		title: "Equation for photosynthesis?",
		questionType: "multiple_choice",
		section: "Equation",
		imageUrl: "",
	},
	{
		exerciseId: 8,
		title: "Main pigment in photosynthesis?",
		questionType: "multiple_choice",
		section: "Pigments",
		imageUrl: "",
	},
	{
		exerciseId: 8,
		title: "Gas released during photosynthesis?",
		questionType: "multiple_choice",
		section: "Products",
		imageUrl: "",
	},
	{
		exerciseId: 8,
		title: "Importance of photosynthesis?",
		questionType: "multiple_choice",
		section: "Applications",
		imageUrl: "",
	},

	// 9. Geometry Problems
	{
		exerciseId: 9,
		title: "Sum of angles in a triangle?",
		questionType: "multiple_choice",
		section: "Triangles",
		imageUrl: "",
	},
	{
		exerciseId: 9,
		title: "Area of a circle formula?",
		questionType: "multiple_choice",
		section: "Circles",
		imageUrl: "",
	},
	{
		exerciseId: 9,
		title: "Number of sides in a hexagon?",
		questionType: "multiple_choice",
		section: "Polygons",
		imageUrl: "",
	},
	{
		exerciseId: 9,
		title: "Pythagoras theorem states?",
		questionType: "multiple_choice",
		section: "Triangles",
		imageUrl: "",
	},
	{
		exerciseId: 9,
		title: "Circumference of circle formula?",
		questionType: "multiple_choice",
		section: "Circles",
		imageUrl: "",
	},

	// 10. Waves and Sound
	{
		exerciseId: 10,
		title: "Define frequency of a wave",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 10,
		title: "Relation between speed, frequency, wavelength?",
		questionType: "multiple_choice",
		section: "Formulas",
		imageUrl: "",
	},
	{
		exerciseId: 10,
		title: "Unit of sound intensity?",
		questionType: "multiple_choice",
		section: "Sound",
		imageUrl: "",
	},
	{
		exerciseId: 10,
		title: "Which wave is sound?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 10,
		title: "Example of transverse wave?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},

	// 11. Acids and Bases
	{
		exerciseId: 11,
		title: "pH of neutral solution?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 11,
		title: "Acids taste?",
		questionType: "multiple_choice",
		section: "Properties",
		imageUrl: "",
	},
	{
		exerciseId: 11,
		title: "Base example?",
		questionType: "multiple_choice",
		section: "Examples",
		imageUrl: "",
	},
	{
		exerciseId: 11,
		title: "Acid + base forms?",
		questionType: "multiple_choice",
		section: "Reactions",
		imageUrl: "",
	},
	{
		exerciseId: 11,
		title: "pH scale range?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},

	// 12. Genetics Basics
	{
		exerciseId: 12,
		title: "Tool used for predicting inheritance?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 12,
		title: "Genotype vs phenotype?",
		questionType: "multiple_choice",
		section: "Definitions",
		imageUrl: "",
	},
	{
		exerciseId: 12,
		title: "Probability of Aa × Aa producing aa?",
		questionType: "multiple_choice",
		section: "Calculations",
		imageUrl: "",
	},
	{
		exerciseId: 12,
		title: "Gregor Mendel studied?",
		questionType: "multiple_choice",
		section: "History",
		imageUrl: "",
	},
	{
		exerciseId: 12,
		title: "Dominant allele represented by?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},

	// 13. Statistics and Probability
	{
		exerciseId: 13,
		title: "Mean of 2,4,6?",
		questionType: "multiple_choice",
		section: "Mean",
		imageUrl: "",
	},
	{
		exerciseId: 13,
		title: "Median of 1,3,5,7,9?",
		questionType: "multiple_choice",
		section: "Median",
		imageUrl: "",
	},
	{
		exerciseId: 13,
		title: "Mode of 2,2,3,4,5?",
		questionType: "multiple_choice",
		section: "Mode",
		imageUrl: "",
	},
	{
		exerciseId: 13,
		title: "Probability of getting head on coin?",
		questionType: "multiple_choice",
		section: "Probability",
		imageUrl: "",
	},
	{
		exerciseId: 13,
		title: "Probability sum rule?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},

	// 14. Electricity and Circuits
	{
		exerciseId: 14,
		title: "Unit of current?",
		questionType: "multiple_choice",
		section: "Basics",
		imageUrl: "",
	},
	{
		exerciseId: 14,
		title: "Ohm’s law equation?",
		questionType: "multiple_choice",
		section: "Formulas",
		imageUrl: "",
	},
	{
		exerciseId: 14,
		title: "Draw a simple circuit",
		questionType: "multiple_choice",
		section: "Diagram",
		imageUrl: "https://example.com/circuit.jpg",
	},
	{
		exerciseId: 14,
		title: "Series vs parallel circuit difference?",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 14,
		title: "What is resistance unit?",
		questionType: "multiple_choice",
		section: "Basics",
		imageUrl: "",
	},

	// 15. Chemical Bonding
	{
		exerciseId: 15,
		title: "Bond between Na and Cl?",
		questionType: "multiple_choice",
		section: "Ionic Bonds",
		imageUrl: "",
	},
	{
		exerciseId: 15,
		title: "Bond in H₂O?",
		questionType: "multiple_choice",
		section: "Covalent Bonds",
		imageUrl: "",
	},
	{
		exerciseId: 15,
		title: "Define ionic bond",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 15,
		title: "Define covalent bond",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
	{
		exerciseId: 15,
		title: "Metallic bonds occur in?",
		questionType: "multiple_choice",
		section: "Applications",
		imageUrl: "",
	},

	// 16. Human Body Systems
	{
		exerciseId: 16,
		title: "Which system pumps blood?",
		questionType: "multiple_choice",
		section: "Circulatory",
		imageUrl: "",
	},
	{
		exerciseId: 16,
		title: "Which system controls breathing?",
		questionType: "multiple_choice",
		section: "Respiratory",
		imageUrl: "",
	},
	{
		exerciseId: 16,
		title: "Which system controls movement?",
		questionType: "multiple_choice",
		section: "Muscular",
		imageUrl: "",
	},
	{
		exerciseId: 16,
		title: "Which system digests food?",
		questionType: "multiple_choice",
		section: "Digestive",
		imageUrl: "",
	},
	{
		exerciseId: 16,
		title: "Which system controls hormones?",
		questionType: "multiple_choice",
		section: "Endocrine",
		imageUrl: "",
	},

	// 17. Trigonometry Basics
	{
		exerciseId: 17,
		title: "sin(30°) equals?",
		questionType: "multiple_choice",
		section: "Ratios",
		imageUrl: "",
	},
	{
		exerciseId: 17,
		title: "cos(60°) equals?",
		questionType: "multiple_choice",
		section: "Ratios",
		imageUrl: "",
	},
	{
		exerciseId: 17,
		title: "tan(45°) equals?",
		questionType: "multiple_choice",
		section: "Ratios",
		imageUrl: "",
	},
	{
		exerciseId: 17,
		title: "Pythagoras theorem in trigonometry?",
		questionType: "multiple_choice",
		section: "Formulas",
		imageUrl: "",
	},
	{
		exerciseId: 17,
		title: "Find opposite side if hypotenuse=10 and sinθ=0.6",
		questionType: "multiple_choice",
		section: "Applications",
		imageUrl: "",
	},

	// 18. Light and Optics
	{
		exerciseId: 18,
		title: "Law of reflection states?",
		questionType: "multiple_choice",
		section: "Reflection",
		imageUrl: "",
	},
	{
		exerciseId: 18,
		title: "Refractive index formula?",
		questionType: "multiple_choice",
		section: "Refraction",
		imageUrl: "",
	},
	{
		exerciseId: 18,
		title: "Convex lens converges or diverges light?",
		questionType: "multiple_choice",
		section: "Lenses",
		imageUrl: "",
	},
	{
		exerciseId: 18,
		title: "Image in plane mirror?",
		questionType: "multiple_choice",
		section: "Mirrors",
		imageUrl: "",
	},
	{
		exerciseId: 18,
		title: "Color dispersion caused by?",
		questionType: "multiple_choice",
		section: "Optics",
		imageUrl: "",
	},

	// 19. States of Matter
	{
		exerciseId: 19,
		title: "Particles in solids are?",
		questionType: "multiple_choice",
		section: "Solids",
		imageUrl: "",
	},
	{
		exerciseId: 19,
		title: "Process from liquid to gas?",
		questionType: "multiple_choice",
		section: "Changes",
		imageUrl: "",
	},
	{
		exerciseId: 19,
		title: "Gas pressure caused by?",
		questionType: "multiple_choice",
		section: "Gases",
		imageUrl: "",
	},
	{
		exerciseId: 19,
		title: "Solid to liquid called?",
		questionType: "multiple_choice",
		section: "Changes",
		imageUrl: "",
	},
	{
		exerciseId: 19,
		title: "Liquid particles arrangement?",
		questionType: "multiple_choice",
		section: "Liquids",
		imageUrl: "",
	},

	// 20. Ecology and Environment
	{
		exerciseId: 20,
		title: "Define ecosystem",
		questionType: "multiple_choice",
		section: "Basics",
		imageUrl: "",
	},
	{
		exerciseId: 20,
		title: "Producer in food chain?",
		questionType: "multiple_choice",
		section: "Food Chains",
		imageUrl: "",
	},
	{
		exerciseId: 20,
		title: "Example of decomposer?",
		questionType: "multiple_choice",
		section: "Food Chains",
		imageUrl: "",
	},
	{
		exerciseId: 20,
		title: "Effect of pollution?",
		questionType: "multiple_choice",
		section: "Environmental Issues",
		imageUrl: "",
	},
	{
		exerciseId: 20,
		title: "Define biodiversity",
		questionType: "multiple_choice",
		section: "Concepts",
		imageUrl: "",
	},
];

export const mockChoices = [
	// Exercise 1: Algebra Practice
	{ questionId: 1, text: "x = 5", isCorrect: true },
	{ questionId: 1, text: "x = 10", isCorrect: false },

	{ questionId: 2, text: "x < 4", isCorrect: true },
	{ questionId: 2, text: "x > 4", isCorrect: false },

	{ questionId: 3, text: "Slope is rise/run", isCorrect: true },
	{ questionId: 3, text: "Slope is x + y", isCorrect: false },

	{ questionId: 4, text: "y = mx + b", isCorrect: true },
	{ questionId: 4, text: "y = ab^x", isCorrect: false },

	{ questionId: 5, text: "x = 3", isCorrect: true },
	{ questionId: 5, text: "x = -3", isCorrect: false },

	// Exercise 2: Newton's Laws
	{ questionId: 6, text: "F = ma", isCorrect: true },
	{ questionId: 6, text: "F = m + a", isCorrect: false },

	{ questionId: 7, text: "Object stays at rest", isCorrect: true },
	{ questionId: 7, text: "Object accelerates forever", isCorrect: false },

	{ questionId: 8, text: "Every action has reaction", isCorrect: true },
	{ questionId: 8, text: "Force disappears instantly", isCorrect: false },

	{ questionId: 9, text: "Inertia", isCorrect: true },
	{ questionId: 9, text: "Momentum", isCorrect: false },

	{ questionId: 10, text: "Friction resists motion", isCorrect: true },
	{ questionId: 10, text: "Friction accelerates motion", isCorrect: false },

	// Exercise 3: Balancing Chemical Equations
	{ questionId: 11, text: "2H2 + O2 → 2H2O", isCorrect: true },
	{ questionId: 11, text: "H2 + O2 → H2O2", isCorrect: false },

	{ questionId: 12, text: "Balanced means atoms conserved", isCorrect: true },
	{ questionId: 12, text: "Balanced means energy is equal", isCorrect: false },

	{ questionId: 13, text: "2Na + Cl2 → 2NaCl", isCorrect: true },
	{ questionId: 13, text: "Na + Cl → NaCl2", isCorrect: false },

	{ questionId: 14, text: "Coefficient changes atom counts", isCorrect: true },
	{ questionId: 14, text: "Subscripts can be changed freely", isCorrect: false },

	{ questionId: 15, text: "Matter is conserved", isCorrect: true },
	{ questionId: 15, text: "Matter is created", isCorrect: false },

	// Exercise 4: Cell Structure
	{ questionId: 16, text: "Nucleus controls cell", isCorrect: true },
	{ questionId: 16, text: "Nucleus makes ATP", isCorrect: false },

	{ questionId: 17, text: "Mitochondria = powerhouse", isCorrect: true },
	{ questionId: 17, text: "Chloroplast = powerhouse", isCorrect: false },

	{ questionId: 18, text: "Ribosomes make proteins", isCorrect: true },
	{ questionId: 18, text: "Ribosomes store DNA", isCorrect: false },

	{ questionId: 19, text: "Cell membrane controls entry", isCorrect: true },
	{ questionId: 19, text: "Cell wall controls entry", isCorrect: false },

	{ questionId: 20, text: "Lysosomes digest waste", isCorrect: true },
	{ questionId: 20, text: "Vacuole digests waste", isCorrect: false },

	// Exercise 5: Quadratic Equations
	{ questionId: 21, text: "x = (-b ± √(b²-4ac))/2a", isCorrect: true },
	{ questionId: 21, text: "x = b² - 4ac", isCorrect: false },

	{ questionId: 22, text: "Quadratic is ax² + bx + c", isCorrect: true },
	{ questionId: 22, text: "Quadratic is ax + b", isCorrect: false },

	{ questionId: 23, text: "Discriminant = b² - 4ac", isCorrect: true },
	{ questionId: 23, text: "Discriminant = a² + b²", isCorrect: false },

	{ questionId: 24, text: "x² - 9 = (x-3)(x+3)", isCorrect: true },
	{ questionId: 24, text: "x² - 9 = (x-9)(x+1)", isCorrect: false },

	{ questionId: 25, text: "Parabola opens up if a>0", isCorrect: true },
	{ questionId: 25, text: "Parabola opens down if a>0", isCorrect: false },

	// Exercise 6: Work and Energy
	{ questionId: 26, text: "Work = Force × Distance", isCorrect: true },
	{ questionId: 26, text: "Work = Mass × Velocity", isCorrect: false },

	{ questionId: 27, text: "Kinetic energy = ½mv²", isCorrect: true },
	{ questionId: 27, text: "Kinetic energy = mv", isCorrect: false },

	{ questionId: 28, text: "Potential energy = mgh", isCorrect: true },
	{ questionId: 28, text: "Potential energy = mgv", isCorrect: false },

	{ questionId: 29, text: "Energy is conserved", isCorrect: true },
	{ questionId: 29, text: "Energy is created", isCorrect: false },

	{ questionId: 30, text: "Joule = unit of work", isCorrect: true },
	{ questionId: 30, text: "Watt = unit of force", isCorrect: false },

	// Exercise 7: Periodic Table
	{ questionId: 31, text: "H is Hydrogen", isCorrect: true },
	{ questionId: 31, text: "H is Helium", isCorrect: false },

	{ questionId: 32, text: "Group 18 = noble gases", isCorrect: true },
	{ questionId: 32, text: "Group 1 = noble gases", isCorrect: false },

	{ questionId: 33, text: "Na is Sodium", isCorrect: true },
	{ questionId: 33, text: "Na is Nitrogen", isCorrect: false },

	{ questionId: 34, text: "Periodic law is atomic number", isCorrect: true },
	{ questionId: 34, text: "Periodic law is atomic mass", isCorrect: false },

	{ questionId: 35, text: "Metals left, nonmetals right", isCorrect: true },
	{ questionId: 35, text: "Metals right, nonmetals left", isCorrect: false },

	// Exercise 8: Photosynthesis
	{ questionId: 36, text: "Occurs in chloroplasts", isCorrect: true },
	{ questionId: 36, text: "Occurs in mitochondria", isCorrect: false },

	{ questionId: 37, text: "Equation: 6CO2+6H2O→C6H12O6+6O2", isCorrect: true },
	{ questionId: 37, text: "Equation: CO2+O2→H2O", isCorrect: false },

	{ questionId: 38, text: "Chlorophyll absorbs sunlight", isCorrect: true },
	{ questionId: 38, text: "Mitochondria absorb sunlight", isCorrect: false },

	{ questionId: 39, text: "Produces glucose", isCorrect: true },
	{ questionId: 39, text: "Produces ATP only", isCorrect: false },

	{ questionId: 40, text: "Light-dependent in thylakoids", isCorrect: true },
	{ questionId: 40, text: "Light-dependent in cytoplasm", isCorrect: false },

	// Exercise 9: Geometry Problems
	{ questionId: 41, text: "Sum of angles in triangle = 180°", isCorrect: true },
	{ questionId: 41, text: "Sum of angles in triangle = 360°", isCorrect: false },

	{ questionId: 42, text: "Area of circle = πr²", isCorrect: true },
	{ questionId: 42, text: "Area of circle = 2πr", isCorrect: false },

	{ questionId: 43, text: "Pythagoras theorem: a²+b²=c²", isCorrect: true },
	{ questionId: 43, text: "a²+b²=c", isCorrect: false },

	{ questionId: 44, text: "Quadrilateral angles sum = 360°", isCorrect: true },
	{ questionId: 44, text: "Quadrilateral angles sum = 180°", isCorrect: false },

	{ questionId: 45, text: "Triangle area = ½ × base × height", isCorrect: true },
	{ questionId: 45, text: "Triangle area = base × height", isCorrect: false },

	// Exercise 10: Waves and Sound
	{ questionId: 46, text: "Frequency = waves/sec", isCorrect: true },
	{ questionId: 46, text: "Frequency = wavelength × speed", isCorrect: false },

	{ questionId: 47, text: "Amplitude = wave height", isCorrect: true },
	{ questionId: 47, text: "Amplitude = wave speed", isCorrect: false },

	{ questionId: 48, text: "Sound needs medium", isCorrect: true },
	{ questionId: 48, text: "Sound travels in vacuum", isCorrect: false },

	{ questionId: 49, text: "Pitch depends on frequency", isCorrect: true },
	{ questionId: 49, text: "Pitch depends on amplitude", isCorrect: false },

	{ questionId: 50, text: "Wave speed = frequency × wavelength", isCorrect: true },
	{ questionId: 50, text: "Wave speed = amplitude × wavelength", isCorrect: false },

	// Exercise 11: Acids and Bases
	{ questionId: 51, text: "pH < 7 = acid", isCorrect: true },
	{ questionId: 51, text: "pH > 7 = acid", isCorrect: false },

	{ questionId: 52, text: "pH > 7 = base", isCorrect: true },
	{ questionId: 52, text: "pH < 7 = base", isCorrect: false },

	{ questionId: 53, text: "HCl is strong acid", isCorrect: true },
	{ questionId: 53, text: "NaOH is acid", isCorrect: false },

	{ questionId: 54, text: "NaOH is strong base", isCorrect: true },
	{ questionId: 54, text: "HCl is base", isCorrect: false },

	{ questionId: 55, text: "Neutral pH = 7", isCorrect: true },
	{ questionId: 55, text: "Neutral pH = 0", isCorrect: false },

	// Exercise 12: Genetics Basics
	{ questionId: 56, text: "Punnett square predicts offspring", isCorrect: true },
	{ questionId: 56, text: "Punnett square predicts parents", isCorrect: false },

	{ questionId: 57, text: "Homozygous = identical alleles", isCorrect: true },
	{ questionId: 57, text: "Homozygous = different alleles", isCorrect: false },

	{ questionId: 58, text: "Heterozygous = different alleles", isCorrect: true },
	{ questionId: 58, text: "Heterozygous = identical alleles", isCorrect: false },

	{ questionId: 59, text: "Dominant allele masks recessive", isCorrect: true },
	{ questionId: 59, text: "Recessive masks dominant", isCorrect: false },

	{ questionId: 60, text: "Genotype is genetic makeup", isCorrect: true },
	{ questionId: 60, text: "Genotype is physical trait", isCorrect: false },

	// Exercise 13: Statistics and Probability
	{ questionId: 61, text: "Mean = sum/n", isCorrect: true },
	{ questionId: 61, text: "Mean = n/sum", isCorrect: false },

	{ questionId: 62, text: "Median is middle value", isCorrect: true },
	{ questionId: 62, text: "Median is average", isCorrect: false },

	{ questionId: 63, text: "Mode = most frequent", isCorrect: true },
	{ questionId: 63, text: "Mode = least frequent", isCorrect: false },

	{ questionId: 64, text: "Probability = favorable/total", isCorrect: true },
	{ questionId: 64, text: "Probability = total/favorable", isCorrect: false },

	{ questionId: 65, text: "Sum of probabilities = 1", isCorrect: true },
	{ questionId: 65, text: "Sum of probabilities = 0", isCorrect: false },

	// Exercise 14: Electricity and Circuits
	{ questionId: 66, text: "Ohm's law: V=IR", isCorrect: true },
	{ questionId: 66, text: "V=I+R", isCorrect: false },

	{ questionId: 67, text: "Series: current same", isCorrect: true },
	{ questionId: 67, text: "Series: voltage same", isCorrect: false },

	{ questionId: 68, text: "Parallel: voltage same", isCorrect: true },
	{ questionId: 68, text: "Parallel: current same", isCorrect: false },

	{ questionId: 69, text: "Power = VI", isCorrect: true },
	{ questionId: 69, text: "Power = V/I", isCorrect: false },

	{ questionId: 70, text: "Resistor limits current", isCorrect: true },
	{ questionId: 70, text: "Resistor increases current", isCorrect: false },

	// Exercise 15: Chemical Bonding
	{ questionId: 71, text: "Ionic = transfer electrons", isCorrect: true },
	{ questionId: 71, text: "Ionic = share electrons", isCorrect: false },

	{ questionId: 72, text: "Covalent = share electrons", isCorrect: true },
	{ questionId: 72, text: "Covalent = transfer electrons", isCorrect: false },

	{ questionId: 73, text: "NaCl is ionic", isCorrect: true },
	{ questionId: 73, text: "H2O is ionic", isCorrect: false },

	{ questionId: 74, text: "H2O is covalent", isCorrect: true },
	{ questionId: 74, text: "NaCl is covalent", isCorrect: false },

	{ questionId: 75, text: "Bonding affects properties", isCorrect: true },
	{ questionId: 75, text: "Bonding has no effect", isCorrect: false },

	// Exercise 16: Human Body Systems
	{ questionId: 76, text: "Heart pumps blood", isCorrect: true },
	{ questionId: 76, text: "Lungs pump blood", isCorrect: false },

	{ questionId: 77, text: "Lungs for respiration", isCorrect: true },
	{ questionId: 77, text: "Lungs digest food", isCorrect: false },

	{ questionId: 78, text: "Brain controls body", isCorrect: true },
	{ questionId: 78, text: "Brain pumps blood", isCorrect: false },

	{ questionId: 79, text: "Stomach digests food", isCorrect: true },
	{ questionId: 79, text: "Stomach stores oxygen", isCorrect: false },

	{ questionId: 80, text: "Kidneys filter blood", isCorrect: true },
	{ questionId: 80, text: "Kidneys digest food", isCorrect: false },

	// Exercise 17: Trigonometry Basics
	{ questionId: 81, text: "sinθ = opposite/hypotenuse", isCorrect: true },
	{ questionId: 81, text: "sinθ = adjacent/hypotenuse", isCorrect: false },

	{ questionId: 82, text: "cosθ = adjacent/hypotenuse", isCorrect: true },
	{ questionId: 82, text: "cosθ = opposite/hypotenuse", isCorrect: false },

	{ questionId: 83, text: "tanθ = opposite/adjacent", isCorrect: true },
	{ questionId: 83, text: "tanθ = adjacent/opposite", isCorrect: false },

	{ questionId: 84, text: "Pythagoras: a²+b²=c²", isCorrect: true },
	{ questionId: 84, text: "a²+b²=c", isCorrect: false },

	{ questionId: 85, text: "Angles in right triangle sum 90°", isCorrect: true },
	{ questionId: 85, text: "Angles sum 180°", isCorrect: false },

	// Exercise 18: Light and Optics
	{ questionId: 86, text: "Reflection = angle in = angle out", isCorrect: true },
	{ questionId: 86, text: "Reflection = angle in = 2×angle out", isCorrect: false },

	{ questionId: 87, text: "Refraction bends light", isCorrect: true },
	{ questionId: 87, text: "Refraction reflects light", isCorrect: false },

	{ questionId: 88, text: "Convex lens converges light", isCorrect: true },
	{ questionId: 88, text: "Convex lens diverges light", isCorrect: false },

	{ questionId: 89, text: "Concave lens diverges light", isCorrect: true },
	{ questionId: 89, text: "Concave lens converges light", isCorrect: false },

	{ questionId: 90, text: "Light travels fastest in vacuum", isCorrect: true },
	{ questionId: 90, text: "Light travels fastest in water", isCorrect: false },

	// Exercise 19: States of Matter
	{ questionId: 91, text: "Solid has fixed shape", isCorrect: true },
	{ questionId: 91, text: "Solid flows easily", isCorrect: false },

	{ questionId: 92, text: "Liquid has fixed volume", isCorrect: true },
	{ questionId: 92, text: "Liquid has fixed shape", isCorrect: false },

	{ questionId: 93, text: "Gas fills container", isCorrect: true },
	{ questionId: 93, text: "Gas has fixed shape", isCorrect: false },

	{ questionId: 94, text: "Melting = solid to liquid", isCorrect: true },
	{ questionId: 94, text: "Melting = liquid to gas", isCorrect: false },

	{ questionId: 95, text: "Boiling = liquid to gas", isCorrect: true },
	{ questionId: 95, text: "Boiling = solid to gas", isCorrect: false },

	// Exercise 20: Ecology and Environment
	{ questionId: 96, text: "Producers make food", isCorrect: true },
	{ questionId: 96, text: "Consumers make food", isCorrect: false },

	{ questionId: 97, text: "Food chain shows energy flow", isCorrect: true },
	{ questionId: 97, text: "Food chain shows water flow", isCorrect: false },

	{ questionId: 98, text: "Ecosystem = community + environment", isCorrect: true },
	{ questionId: 98, text: "Ecosystem = only animals", isCorrect: false },

	{ questionId: 99, text: "Pollution harms environment", isCorrect: true },
	{ questionId: 99, text: "Pollution helps environment", isCorrect: false },

	{ questionId: 100, text: "Recycling reduces waste", isCorrect: true },
	{ questionId: 100, text: "Recycling increases waste", isCorrect: false },
];

export const mockUsers = [
    {
        uid: "1",
        username: "sokchea01",
        firstName: "Sokchea",
        lastName: "Chan",
        dateOfBirth: "2005-03-15",
        isAdmin: false,
        isVerified: true,
        isSocial: false,
        email: "sokchea01@example.com",
        phone: "012345678",
        profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
        profileImageKey: "profile1",
    },
    {
        uid: "2",
        username: "rathana02",
        firstName: "Rathana",
        lastName: "Sok",
        dateOfBirth: "2004-07-22",
        isAdmin: false,
        isVerified: true,
        isSocial: false,
        email: "rathana02@example.com",
        phone: "012345679",
        profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
        profileImageKey: "profile2",
    },
    {
        uid: "3",
        username: "sreyleak03",
        firstName: "Sreyleak",
        lastName: "Phan",
        dateOfBirth: "2006-01-10",
        isAdmin: false,
        isVerified: false,
        isSocial: true,
        email: "sreyleak03@example.com",
        phone: "012345680",
        profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
        profileImageKey: "profile3",
    },
    {
        uid: "4",
        username: "vannak04",
        firstName: "Vannak",
        lastName: "Lim",
        dateOfBirth: "2005-11-05",
        isAdmin: false,
        isVerified: true,
        isSocial: false,
        email: "vannak04@example.com",
        phone: "012345681",
        profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
        profileImageKey: "profile4",
    },
    {
        uid: "5",
        username: "dara05",
        firstName: "Dara",
        lastName: "Kim",
        dateOfBirth: "2004-09-18",
        isAdmin: false,
        isVerified: false,
        isSocial: false,
        email: "dara05@example.com",
        phone: "012345682",
        profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
        profileImageKey: "profile5",
    },
    {
        uid: "6",
        username: "sophea06",
        firstName: "Sophea",
        lastName: "Yim",
        dateOfBirth: "2005-05-30",
        isAdmin: false,
        isVerified: true,
        isSocial: true,
        email: "sophea06@example.com",
        phone: "012345683",
        profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
        profileImageKey: "profile6",
    },
    {
        uid: "7",
        username: "piseth07",
        firstName: "Piseth",
        lastName: "Oum",
        dateOfBirth: "2006-02-14",
        isAdmin: false,
        isVerified: false,
        isSocial: false,
        email: "piseth07@example.com",
        phone: "012345684",
        profileImage: "https://randomuser.me/api/portraits/men/7.jpg",
        profileImageKey: "profile7",
    },
    {
        uid: "8",
        username: "sokunthea08",
        firstName: "Sokunthea",
        lastName: "Chhim",
        dateOfBirth: "2005-08-25",
        isAdmin: false,
        isVerified: true,
        isSocial: false,
        email: "sokunthea08@example.com",
        phone: "012345685",
        profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
        profileImageKey: "profile8",
    },
    {
        uid: "9",
        username: "borey09",
        firstName: "Borey",
        lastName: "Suon",
        dateOfBirth: "2004-12-12",
        isAdmin: false,
        isVerified: false,
        isSocial: false,
        email: "borey09@example.com",
        phone: "012345686",
        profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
        profileImageKey: "profile9",
    },
    {
        uid: "10",
        username: "mony10",
        firstName: "Mony",
        lastName: "Sann",
        dateOfBirth: "2005-04-03",
        isAdmin: false,
        isVerified: true,
        isSocial: true,
        email: "mony10@example.com",
        phone: "012345687",
        profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
        profileImageKey: "profile10",
    },
    {
        uid: "11",
        username: "sokha11",
        firstName: "Sokha",
        lastName: "Chea",
        dateOfBirth: "2006-06-20",
        isAdmin: false,
        isVerified: false,
        isSocial: false,
        email: "sokha11@example.com",
        phone: "012345688",
        profileImage: "https://randomuser.me/api/portraits/men/11.jpg",
        profileImageKey: "profile11",
    },
    {
        uid: "12",
        username: "sreypov12",
        firstName: "Sreypov",
        lastName: "Hem",
        dateOfBirth: "2005-10-28",
        isAdmin: false,
        isVerified: true,
        isSocial: false,
        email: "sreypov12@example.com",
        phone: "012345689",
        profileImage: "https://randomuser.me/api/portraits/women/12.jpg",
        profileImageKey: "profile12",
    },
    {
        uid: "13",
        username: "vichea13",
        firstName: "Vichea",
        lastName: "Khim",
        dateOfBirth: "2004-08-16",
        isAdmin: false,
        isVerified: false,
        isSocial: false,
        email: "vichea13@example.com",
        phone: "012345690",
        profileImage: "https://randomuser.me/api/portraits/men/13.jpg",
        profileImageKey: "profile13",
    },
    {
        uid: "14",
        username: "sokny14",
        firstName: "Sokny",
        lastName: "Meas",
        dateOfBirth: "2005-02-09",
        isAdmin: false,
        isVerified: true,
        isSocial: false,
        email: "sokny14@example.com",
        phone: "012345691",
        profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
        profileImageKey: "profile14",
    },
    {
        uid: "15",
        username: "rith15",
        firstName: "Rith",
        lastName: "Chau",
        dateOfBirth: "2006-03-21",
        isAdmin: false,
        isVerified: false,
        isSocial: true,
        email: "rith15@example.com",
        phone: "012345692",
        profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
        profileImageKey: "profile15",
    },
    {
        uid: "16",
        username: "sreyneang16",
        firstName: "Sreyneang",
        lastName: "Sok",
        dateOfBirth: "2005-07-13",
        isAdmin: false,
        isVerified: true,
        isSocial: false,
        email: "sreyneang16@example.com",
        phone: "012345693",
        profileImage: "https://randomuser.me/api/portraits/women/16.jpg",
        profileImageKey: "profile16",
    },
    {
        uid: "17",
        username: "sokun17",
        firstName: "Sokun",
        lastName: "Chhay",
        dateOfBirth: "2004-11-29",
        isAdmin: false,
        isVerified: false,
        isSocial: false,
        email: "sokun17@example.com",
        phone: "012345694",
        profileImage: "https://randomuser.me/api/portraits/men/17.jpg",
        profileImageKey: "profile17",
    },
    {
        uid: "18",
        username: "sreymom18",
        firstName: "Sreymom",
        lastName: "Peou",
        dateOfBirth: "2005-06-07",
        isAdmin: false,
        isVerified: true,
        isSocial: false,
        email: "sreymom18@example.com",
        phone: "012345695",
        profileImage: "https://randomuser.me/api/portraits/women/18.jpg",
        profileImageKey: "profile18",
    },
    {
        uid: "19",
        username: "sokheng19",
        firstName: "Sokheng",
        lastName: "Pov",
        dateOfBirth: "2006-01-25",
        isAdmin: false,
        isVerified: false,
        isSocial: false,
        email: "sokheng19@example.com",
        phone: "012345696",
        profileImage: "https://randomuser.me/api/portraits/men/19.jpg",
        profileImageKey: "profile19",
    },
    {
        uid: "20",
        username: "sreynich20",
        firstName: "Sreynich",
        lastName: "Kea",
        dateOfBirth: "2005-09-02",
        isAdmin: true,
        isVerified: true,
        isSocial: true,
        email: "sreynich20@example.com",
        phone: "012345697",
        profileImage: "https://randomuser.me/api/portraits/women/20.jpg",
        profileImageKey: "profile20",
    },
];
