type DataItem = {
	title: string;
	description: string;
	type: string;
	topic: string;
};

export const data: DataItem[] = [
	{
		title: "Challenges of Learning Math in Cambodian High Schools",
		description: "Many students find math difficult due to large class sizes and limited resources.",
		type: "educational",
		topic: "math",
	},
	{
		title: "វិធីសាស្រ្តសិក្សាដែលមានប្រសិទ្ធភាពសម្រាប់មធ្យមសិក្សា",
		description: "ការរៀនប្រកបដោយប្រព័ន្ធ និងការអនុវត្តន៍ជាក់ស្តែងជួយឲ្យសិស្សមានជោគជ័យ។",
		type: "educational",
		topic: "study methods",
	},
	{
		title: "The Importance of English for Cambodian Teens",
		description: "Learning English opens opportunities for higher education and future careers.",
		type: "educational",
		topic: "english",
	},
	{
		title: "ការរីកចម្រើននៃវិទ្យាសាស្ត្រនៅសាលាមធ្យមសិក្សា",
		description: "វិទ្យាសាស្ត្រ ជាគន្លងសំខាន់សម្រាប់ការអភិវឌ្ឍប្រទេស។",
		type: "educational",
		topic: "science",
	},
	{
		title: "How to Improve Study Habits in High School",
		description: "This post discusses practical strategies for students to improve their learning habits.",
		type: "educational",
		topic: "study methods",
	},
	{
		title: "តួនាទីរបស់គ្រូនៅក្នុងការអប់រំកម្ពុជា",
		description: "គ្រូមានតួនាទីសំខាន់ក្នុងការបណ្តុះបណ្តាល និងណែនាំសិស្សក្នុងមធ្យមសិក្សា។",
		type: "educational",
		topic: "teachers",
	},
	{
		title: "Effective Time Management for Students",
		description: "Managing time effectively helps students balance studies, hobbies, and exams.",
		type: "educational",
		topic: "time management",
	},
	{
		title: "ការគ្រប់គ្រងពេលវេលាដែលមានប្រសិទ្ធភាពសម្រាប់សិស្ស",
		description: "ការគ្រប់គ្រងពេលវេលាឱ្យមានប្រសិទ្ធភាពជួយសិស្សធ្វើតុល្យភាពរវាងការសិក្សា និងការសម្រាក។",
		type: "educational",
		topic: "time management",
	},
	{
		title: "Preparing for the Bac II Exam Successfully",
		description: "Preparing early for exams ensures better results and reduces stress.",
		type: "educational",
		topic: "exam preparation",
	},
	{
		title: "ការរៀបចំសម្រាប់ប្រឡង Bac II",
		description: "ការរៀបចំមុនពេលប្រឡងធ្វើឱ្យសិស្សទទួលបានលទ្ធផលល្អ និងកាត់បន្ថយសំពាធ។",
		type: "educational",
		topic: "exam preparation",
	},
	{
		title: "Overcoming Stress During High School",
		description: "Students face stress, but proper planning and breaks help overcome it.",
		type: "educational",
		topic: "mental health",
	},
	{
		title: "ការកាត់បន្ថយសំពាធនៅក្នុងមធ្យមសិក្សា",
		description: "សិស្សជួបសំពាធ ប៉ុន្តែការធ្វើផែនការល្អ និងការសម្រាកជួយឱ្យកាត់បន្ថយវា។",
		type: "educational",
		topic: "mental health",
	},
	{
		title: "Importance of Reading for Students",
		description: "Reading regularly enhances knowledge and critical thinking skills.",
		type: "educational",
		topic: "reading",
	},
	{
		title: "សារៈសំខាន់នៃការអានសម្រាប់សិស្ស",
		description: "ការអានជាប្រចាំបង្កើនចំណេះដឹង និងជំនាញគិតវិចារណញ្ញា។",
		type: "educational",
		topic: "reading",
	},
	{
		title: "Learning English as a Second Language",
		description: "English is essential for higher education and global opportunities.",
		type: "educational",
		topic: "english",
	},
	{
		title: "ការសិក្សាភាសាអង់គ្លេសជាភាសាទីពីរ",
		description: "ការសិក្សាភាសាអង់គ្លេសមានសារៈសំខាន់សម្រាប់ការអប់រំខ្ពស់ និងឱកាសអន្តរជាតិ។",
		type: "educational",
		topic: "english",
	},
	{
		title: "Exploring Career Options After High School",
		description: "Exploring career options early helps students make informed decisions.",
		type: "educational",
		topic: "career",
	},
	{
		title: "ការស្វែងរកជម្រើសមុខវិជ្ជាផ្សេងៗបន្ទាប់ពីមធ្យមសិក្សា",
		description: "ការស្វែងរកជម្រើសមុខវិជ្ជាពីមុនជួយសិស្សធ្វើការសម្រេចចិត្តបានឆ្លាតវៃ។",
		type: "educational",
		topic: "career",
	},
	{
		title: "Balancing Sports and Academics",
		description: "Students benefit from extracurricular activities, but academics must come first.",
		type: "educational",
		topic: "balance",
	},
	{
		title: "តុល្យភាពរវាងកីឡា និងសិក្សា",
		description: "ការចូលរួមក្នុងសកម្មភាពក្រៅម៉ោងអាចជួយសិស្សបង្កើនជំនាញ ប៉ុន្តែការសិក្សាអាចមិនត្រូវអោយខកខាន។",
		type: "educational",
		topic: "balance",
	},
	{
		title: "Using Technology to Learn Effectively",
		description: "Online platforms and educational apps can enhance learning experiences.",
		type: "educational",
		topic: "technology",
	},
	{
		title: "ការប្រើបច្ចេកវិទ្យាដើម្បីសិក្សាបានប្រសើរ",
		description: "វេទិកាអនឡាញ និងកម្មវិធីអប់រំជួយសិស្សក្នុងការសិក្សាបានប្រសើរ។",
		type: "educational",
		topic: "technology",
	},
	{
		title: "Group Study Tips for High School Students",
		description: "Studying with peers can increase understanding and motivation.",
		type: "educational",
		topic: "group study",
	},
	{
		title: "យុទ្ធសាស្រ្តរៀនជាក្រុមសម្រាប់សិស្សមធ្យមសិក្សា",
		description: "ការរៀនជាក្រុមជួយសិស្សបង្កើនការយល់ដឹង និងកម្លាំងចិត្ត។",
		type: "educational",
		topic: "group study",
	},
	{
		title: "Effective Note-Taking Strategies",
		description: "Taking organized notes improves memory retention and exam performance.",
		type: "educational",
		topic: "note-taking",
	},
	{
		title: "យុទ្ធសាស្រ្តកត់ចំណាំមានប្រសិទ្ធភាព",
		description: "ការកត់ចំណាំដោយច្បាស់អាចជួយបង្កើនការចងចាំ និងលទ្ធផលប្រឡង។",
		type: "educational",
		topic: "note-taking",
	},
	{
		title: "How to Stay Motivated in High School",
		description: "Set goals, reward yourself, and stay consistent to maintain motivation.",
		type: "educational",
		topic: "motivation",
	},
	{
		title: "របៀបរកកម្លាំងចិត្តនៅក្នុងមធ្យមសិក្សា",
		description: "កំណត់គោលដៅ ផ្តល់រង្វាន់ខ្លួនឯង និងរក្សាទម្លាប់ល្អ។",
		type: "educational",
		topic: "motivation",
	},
	{
		title: "The Role of Parents in Education",
		description: "Parental involvement is key to student success and discipline.",
		type: "educational",
		topic: "parents",
	},
	{
		title: "តួនាទីរបស់មាតាបិតា ក្នុងការអប់រំ",
		description: "ការចូលរួមរបស់មាតាបិតាជាកត្តាសំខាន់សម្រាប់ភាពជោគជ័យរបស់សិស្ស។",
		type: "educational",
		topic: "parents",
	},
	{
		title: "Tips for Improving Writing Skills",
		description: "Regular practice and reading widely improves essay writing.",
		type: "educational",
		topic: "writing",
	},
	{
		title: "យុទ្ធសាស្រ្តបង្កើនជំនាញសរសេរ",
		description: "ការអនុវត្តជាប្រចាំ និងការអានជាច្រើនជួយបង្កើនជំនាញសរសេរ។",
		type: "educational",
		topic: "writing",
	},
	{
		title: "Understanding Science Concepts Easily",
		description: "Hands-on experiments help students grasp scientific concepts better.",
		type: "educational",
		topic: "science",
	},
	{
		title: "ការយល់ដឹងពីមុខវិជ្ជាវិទ្យាសាស្ត្រងាយៗ",
		description: "ការធ្វើពិសោធន៍ជាក់ស្តែងជួយសិស្សយល់បានល្អ។",
		type: "educational",
		topic: "science",
	},
	{
		title: "Overcoming Procrastination",
		description: "Plan ahead, set small tasks, and eliminate distractions to finish work on time.",
		type: "educational",
		topic: "productivity",
	},
	{
		title: "ការជៀសវាងការពន្យារពេល",
		description: "រៀបចំផែនការ កំណត់ភារកិច្ចតូចៗ និងបញ្ចេញការរំខាន។",
		type: "educational",
		topic: "productivity",
	},
	{
		title: "How to Participate Actively in Class",
		description: "Ask questions, engage in discussions, and contribute ideas.",
		type: "educational",
		topic: "participation",
	},
	{
		title: "របៀបចូលរួមសកម្មភាពថ្នាក់",
		description: "សួរពីចម្ងល់ ចូលរួមពិភាក្សា និងចែករំលែកគំនិត។",
		type: "educational",
		topic: "participation",
	},
	{
		title: "Importance of Attendance",
		description: "Regular attendance ensures continuity in learning and understanding.",
		type: "educational",
		topic: "attendance",
	},
	{
		title: "សារៈសំខាន់នៃការចូលរៀន",
		description: "ការចូលរៀនជាប្រចាំធានាការបន្តការសិក្សា និងការយល់ដឹង។",
		type: "educational",
		topic: "attendance",
	},
	{
		title: "How to Prepare for Group Projects",
		description: "Divide tasks fairly, communicate well, and meet deadlines.",
		type: "educational",
		topic: "group projects",
	},
	{
		title: "របៀបរៀបចំគម្រោងក្រុម",
		description: "ចែកចំណែកភារកិច្ចយ៉ាងសមរម្យ ចាប់អារម្មណ៍ និងគោរពពេលកំណត់។",
		type: "educational",
		topic: "group projects",
	},
	{
		title: "Building Confidence in Public Speaking",
		description: "Practice, prepare, and stay calm to speak confidently in front of peers.",
		type: "educational",
		topic: "public speaking",
	},
	{
		title: "ការបង្កើនទំនុកចិត្តក្នុងការនិយាយសាធារណៈ",
		description: "អនុវត្ត រៀបចំ និងរក្សាស្ងប់ស្ងាត់។",
		type: "educational",
		topic: "public speaking",
	},
	{
		title: "Learning from Mistakes",
		description: "Mistakes are learning opportunities; analyze and improve.",
		type: "educational",
		topic: "growth mindset",
	},
	{
		title: "ការរៀនពីកំហុស",
		description: "កំហុសជាឱកាសរៀន; វិភាគ និងកែលម្អ។",
		type: "educational",
		topic: "growth mindset",
	},
	{
		title: "Effective Revision Techniques",
		description: "Use flashcards, summaries, and practice tests to revise efficiently.",
		type: "educational",
		topic: "revision",
	},
	{
		title: "យុទ្ធសាស្រ្តពិនិត្យវិញមានប្រសិទ្ធភាព",
		description: "ប្រើកាតរំលឹក សេចក្តីសង្ខេប និងការប្រឡងសាកល្បង។",
		type: "educational",
		topic: "revision",
	},
	{
		title: "Developing Critical Thinking Skills",
		description: "Question assumptions and analyze information critically.",
		type: "educational",
		topic: "critical thinking",
	},
	{
		title: "ការអភិវឌ្ឍជំនាញគិតវិចារណញ្ញា",
		description: "សួរពីការសន្មត់ និងវិភាគព័ត៌មានយ៉ាងម៉ត់ចត់។",
		type: "educational",
		topic: "critical thinking",
	},
	{
		title: "How to Write a Good Essay",
		description: "Plan structure, support arguments with examples, and proofread.",
		type: "educational",
		topic: "writing",
	},
	{
		title: "របៀបសរសេរអត្ថបទល្អ",
		description: "រៀបចំរចនាសម្ព័ន្ធ គាំទ្រពត៌មានដោយឧទាហរណ៍ និងពិនិត្យមើលម្ដងទៀត។",
		type: "educational",
		topic: "writing",
	},
	{
		title: "Time Management for Exam Weeks",
		description: "Prioritize subjects, avoid distractions, and create a study timetable.",
		type: "educational",
		topic: "time management",
	},
	{
		title: "ការគ្រប់គ្រងពេលវេលាសម្រាប់សប្តាហ៍ប្រឡង",
		description: "អាទិភាពផ្ដល់ឱ្យមុខវិជ្ជា ចៀសវាងការរំខាន និងបង្កើតកាលវិភាគសិក្សា។",
		type: "educational",
		topic: "time management",
	},
];

export const comments = [
	"This post really helped me understand the challenges in high school! 📚💡",
	"អត្ថបទនេះមានប្រយោជន៍ខ្លាំងសម្រាប់សិស្សនៅមធ្យមសិក្សា 🎓✨",
	"I love the tips about balancing sports and studies ⚽📖",
	"ខ្ញុំចូលចិត្តផ្នែកដែលនិយាយអំពីការគ្រប់គ្រងពេលវេលា ⏰📝",
	"Very helpful advice on managing stress during exams 😌📝",
	"ខ្ញុំពិតជាស្វែងយល់ពីយុទ្ធសាស្រ្តពិនិត្យវិញនេះ 📖✨",
	"These note-taking tips are awesome! 📝👍",
	"ខ្ញុំនឹងអនុវត្តវិធីសាស្រ្តកត់ចំណាំនេះពិតណាស់ 📚💪",
	"I didn’t know educational apps could be so useful! 📱💡",
	"ខ្ញុំយល់ព្រម! ការអនុវត្តប្រើកម្មវិធីអប់រំជួយសិក្សាអោយបានល្អ 🎓😊",
	"Really love how this article explains exam preparation ✏️🧠",
	"ការរៀបចំប្រឡងតាមអត្ថបទនេះជួយខ្ញុំយល់បានច្បាស់ 📖💯",
	"Reading habits are so important! 📚❤️",
	"អត្ថបទនេះជំរុញឱ្យខ្ញុំអានជាប្រចាំ 🎓✨",
	"I’ll try these group study strategies with my friends 👩‍🎓👨‍🎓",
	"យុទ្ធសាស្រ្តរៀនជាក្រុមនេះពិតជាមានប្រយោជន៍ 💡📖",
	"Thanks for explaining the importance of mental health during exams 🧘‍♂️💙",
	"អត្ថបទនេះបង្ហាញពីសារៈសំខាន់នៃសុខភាពផ្លូវចិត្ត 🧘‍♀️✨",
	"Love the practical examples provided in this post 👏📚",
	"ខ្ញុំចូលចិត្តឧទាហរណ៍ជាក់ស្តែងក្នុងអត្ថបទនេះ 🎓💡",
];

export const replies = [
	"Absolutely! These tips are so practical 🙌",
	"Thanks for sharing! I’ll try them in my next exam 😄",
	"Agreed! Very insightful 💯",
	"ពិតណាស់! វាជួយខ្ញុំរៀនប្រកបដោយប្រព័ន្ធ 📖",
	"ខ្ញុំសូមអរគុណសម្រាប់ការចែករំលែកនេះ 😊",
	"អត្ថបទនេះមានប្រយោជន៍ណាស់! 🎓✨",
	"Same here! Maintaining balance is so important 👍",
	"Great advice, I’m going to follow it 💪",
	"I’ll share it with my classmates too 😄",
	"យុទ្ធសាស្រ្តនេះពិតជាមានប្រយោជន៍ 😄",
	"ខ្ញុំនឹងអនុវត្តវាឱ្យបានត្រឹមត្រូវ 💯",
	"សូមអរគុណច្រើន! 📚✨",
	"I will try these strategies next exam! ✏️📖",
	"Super helpful, thanks! 🌟",
	"Definitely useful tips! 👍",
	"ខ្ញុំបានរៀនច្រើនពីអត្ថបទនេះ 🎓",
	"វាជួយខ្ញុំបង្កើនការយល់ដឹង 💡",
	"មិនអាចជឿបានថាវាមានប្រយោជន៍បានច្រើននេះ 😄",
	"Can’t wait to use these note-taking methods 📝✨",
	"This will make studying so much easier 😄",
	"I’m going to share with my study group 👍",
	"ពិតណាស់! វាជួយខ្ញុំចងចាំបានល្អ 📚",
	"ខ្ញុំស្វែងយល់ពីវាច្រើន 👍",
	"ខ្ញុំសូមអរគុណច្រើន! 🎓",
	"I’m downloading these educational apps now! 📱😊",
	"Thanks for the recommendation 💡",
	"These apps seem really fun 😄📚",
	"វាពិតជាមានប្រយោជន៍ខ្លាំង 🎓",
	"ខ្ញុំនឹងអនុវត្តវាឱ្យបានត្រឹមត្រូវ 💯",
	"អត្ថបទនេះពិតជាជួយខ្ញុំបានច្រើន 😄",
	"Great advice for exam prep! ✏️💡",
	"I’ll start using these tips today 📖👍",
	"Thanks! This is super helpful 😊",
	"ការរៀបចំប្រឡងតាមអត្ថបទនេះជួយខ្ញុំយល់បានច្បាស់ 📖💯",
	"ខ្ញុំនឹងអនុវត្តវា 💪",
	"ពិតជាមានប្រយោជន៍ណាស់! 🎓",
	"Reading habits are life-changing! 📚❤️",
	"I’m going to read more starting today ✨",
	"អត្ថបទនេះជំរុញខ្ញុំបានច្រើន 🎓📖",
	"I’ll try these group study strategies with my friends 👩‍🎓👨‍🎓",
	"Sounds fun! We’ll start this week 💪",
	"Great idea! Teamwork helps a lot 😄",
	"Thanks for explaining the importance of mental health 🧘‍♂️💙",
	"Very important reminder 😌",
	"ខ្ញុំយល់ព្រម! វាជួយខ្ញុំរក្សាសុខភាពផ្លូវចិត្ត 🧘‍♀️✨",
	"Love the practical examples shared 👏📚",
	"ខ្ញុំចូលចិត្តឧទាហរណ៍ជាក់ស្តែងក្នុងអត្ថបទនេះ 🎓💡",
];
